### ISSUE TITLE
Release your debian folder

### ISSUE THREAD

**Issue by aviau** [influxdb/influxdb#1026]
Hello!

I have filled an Intention to package for influxdb in Debian here: https://bugs.debian.org/765005

I would like to know if you could release your current debian packaging so that I can work from there.

Until then, I have begun working here: https://github.com/ReAzem/influxdb/tree/0.8.3-1

Thanks,

**Comment by danieldreier** [comment]
One way or another, influxdb should be available as an apt package repository. Given that you're already building dpkg files, this should be basically trivial; you can push the apt repository into S3 as part of the dpkg build process. 

I'd be glad to help, because without official repositories I either have to build my own or write an awkward puppet module that works around the lack of proper repositories.

**Comment by otoolep** [comment]
We have discussed this internally, because the advent of a pure-Go build for the 0.9.0 release makes builds much cleaner. We're planning to release proper packages -- and distribute them well -- for various distros during the 0.9.0 timeframe.

**Comment by danieldreier** [comment]
That's fantastic. I really appreciate the update. Thanks!

**Comment by randywallace** [comment]
-1 for pushing InfluxDB to mainstream Debian.

Upstream/Mainstream packaging is guaranteed to cause conflicts with "Breaking Changes" which, for example, will result in unnecessary pain in github issues, backporting, automatic upgrades, and non-obvious versioned package names, like influxdb0_9.  It likewise implies that you can just upgrade a package and the data will be magically migrated/updated/upgraded for you if not for the large message during upgrade that tells you otherwise, which a percentage of users are guaranteed to miss.  Then some maintainer for a further upstream distro (Lookin' at you Ubuntu) will specify a metapackage (i.e. influxdb => influxdb0_9), and somehow users end up in a state in which they're pinning packages b/c they don't want to install X11 or the apache webserver or upgrade influxdb to the next major version.  A whole lot of pain that is just not worth the time.

Does anyone actually run databases in production from disto repos?  MySQL?  PostgreSQL?  Elasticsearch? ... Graphite?

I say the time is better spent making InfluxDB brilliantly awesome functionally.  Leave us users with the task of following a few basic install steps or spending the time to write a puppet/chef/ansible/dockerfile/whatever to do it for us... at least until 1.0 :)

**Comment by danieldreier** [comment]
@randywallace I may have miscommunicated here -- I'm absolutely not asking for Debian/CentOS packages to be included in the official Debian repos. I'd just like official influxdb package repos that keep pace with actual releases, with no need to get those merged into the distro.

For example, I run mariadb from the mariadb debian packages (http://mariadb.org/mariadb/repositories/), postgresql from their official repo (apt.postgresql.org) etc. Installing packages with puppet/chef/whatever is enormously easier when packages are available, because you separate out the release engineering concern (how to build, writing init scripts, dependency management, etc) from the install/configure task.

My recommendation would be that we add publication to a hosted repo like [bintray](http://blog.bintray.com/2014/12/16/hosting-debian-packages-on-bintray-rocks/) to whatever the existing release process is; it's basically a matter of posting the existing apt/yum/whatever packages to their REST API (or doing it manually, for now).

Alternatively, I'd be glad to help y'all set up an S3-hosted apt repository.

**Comment by justin8** [comment]
As you mentioned using puppet/chef/etc, there is already a puppet module for diamond that works pretty well, you can use the packaged version for ones where it is available like Arch or let it manage the pip installed version for places where it isn't. That being said, +1 to deb/rpm packages, although I would prefer them upstream as well eventually.

**Comment by aviau** [comment]
During the past weeks, I have packaged the following InfluxDB dependencies (direct and undirect) for Debian:

- [golang-collectd](https://tracker.debian.org/pkg/golang-collectd)
- [golang-github-armon-go-metrics](https://tracker.debian.org/pkg/golang-github-armon-go-metrics)
- [golang-github-bmizerany-pat](https://tracker.debian.org/pkg/golang-github-bmizerany-pat)
- [golang-github-boltdb-bolt](https://tracker.debian.org/pkg/golang-github-boltdb-bolt)
- [golang-github-davecgh-go-spew](https://tracker.debian.org/pkg/golang-github-davecgh-go-spew)
- [golang-github-hashicorp-go-msgpack](https://tracker.debian.org/pkg/golang-github-hashicorp-go-msgpack)
- [golang-github-hashicorp-raft](https://tracker.debian.org/pkg/golang-github-hashicorp-raft)
- [golang-github-hashicorp-raft-boltdb](https://tracker.debian.org/pkg/golang-github-hashicorp-raft-boltdb)
- [golang-github-kimor79-gollectd](https://tracker.debian.org/pkg/golang-github-kimor79-gollectd)
- [golang-github-peterh-liner](https://tracker.debian.org/pkg/golang-github-peterh-liner)
- [golang-github-rakyll-statik](https://tracker.debian.org/pkg/golang-github-rakyll-statik)
- [golang-github-ugorji-go-codec](https://tracker.debian.org/pkg/golang-github-ugorji-go-codec)
- [golang-github-ugorji-go-msgpack](https://tracker.debian.org/pkg/golang-github-ugorji-go-msgpack)
- [golang-gopkg-fatih-pool.v2](https://tracker.debian.org/pkg/golang-gopkg-fatih-pool.v2)
- [golang-gopkg-mgo.v2](https://tracker.debian.org/pkg/golang-gopkg-mgo.v2)
- [golang-gopkg-tomb.v2](https://tracker.debian.org/pkg/golang-gopkg-tomb.v2)
- [golang-gopkg-vmihailenco-msgpack.v2](https://tracker.debian.org/pkg/golang-gopkg-vmihailenco-msgpack.v2)

As of today, [InfluxDB 0.9.2](https://packages.qa.debian.org/i/influxdb.html) is available in the Debian unstable repos.

Debian packages are automatically imported by Ubuntu. InfluxDB should therefore be available in Ubuntu in the next few days.

I intend to keep maintaining the InfluxDB ecosystem in Debian. For example, Telegraf is almost ready and InfluxDB 0.9.2.1 is on its way.

**Comment by otoolep** [comment]
Thanks @aviau
