### ISSUE TITLE
ldap or active directory password authentication for influxdb web UI

### ISSUE THREAD

**Issue by tjyang** [influxdb/influxdb#1205]
Hi, 
This is a feature request for future version of influxdb UI. I am hoping to be able to create admin account but having password authentication from LDAP server or Windows Active Directory server.

**Comment by BartVB** [comment]
@kureikain is that configuration working for you?
I can't get the admin up & running with proxy_pass. The admin seems to expect that InfluxDB runs on the root of the webserver. Because of that assets don't load in the admin (they are hardcoded to use /images/ etc). Besides that it's impossible to specify the API endpoint in the admin. I would like the admin to talk to:

http://statsserver.domain.com/influxdb/ instead of http://root:root@127.0.0.1:8083/ but I can't specify the '/influxdb/' part and the username/password can't be empty.

This is the config I'm currently using:

```
  location / {
    root  /var/www/sites/myserver/;
    index  index.html  index.htm;
    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/myserver.htpasswd;
  }

  location /influx-admin/ {
    rewrite /influx-admin/(.*) /$1 break;
    # proxy_set_header Authorization "Basic cm9vdDpyb290";
    proxy_pass http://127.0.0.1:8083;
  }

  location /influx/ {
    rewrite /influx/(.*) /$1 break;
    proxy_set_header Authorization "Basic cm9vdDpyb290";
    proxy_pass http://127.0.0.1:8086;
  }
```

This works with Grafana but not with the built in Admin.

**Comment by pauldix** [comment]
Adding LDAP/AD support to InfluxDB is outside the scope of what we're going to do with the web UI. Later this year we'll have a product out that adds more security features, but that'll be a separate thing that you put in front of InfluxDB.
