### ISSUE TITLE
Can't select specific point on downsampled data

### ISSUE THREAD

**Issue by vforgione** [influxdb/influxdb#1290]
When perform a general query

```bash
curl -G "http://example.com:8086/db/influxdb/series?u=root&p=root&pretty=true" --data-urlencode "q=select * from 1d.percentile.top_tenth.example"
```

I get the expected result

```json
[
    {
        "name": "1d.percentile.top_tenth.example",
        "columns": [
            "time",
            "sequence_number",
            "percentile"
        ],
        "points": [
            [
                1420329600000,
                1,
                1262
            ],
            ...
        ]
    }
]
```

However, if I try to select a specific point, as in the [documented pattern](http://influxdb.com/docs/v0.7/api/query_language.html#selecting-a-specific-point)

```bash
curl -G "http://example.com:8086/db/influxdb/series?u=root&p=root&pretty=true" --data-urlencode "q=select * from 1d.percentile.top_tenth.example where time = 1420329600000 and sequence_number = 1"
```

I get an empty result

```json
[]
```

I'm not sure if this is an API issue or if it's because I'm querying on a downsampled series with aggregate data and that isn't supported (the continuous query used for the series is `select percentile(clicks, 99.9) from example group by time(1d) into 1d.percentile.top_tenth.example`)

**Comment by akloeber** [comment]
I ran into the same issue and it has nothing to do with downsampling as it can be reproduced from scratch like this:

    # Create database
    curl -X POST 'http://localhost:8086/db?u=root&p=root' -d '{"name": "test"}'

    # Write point
    curl -X POST 'http://localhost:8086/db/test/series?u=root&p=root&time_precision=u' -d '[{"columns":["time","value"],"name":"ts","points":[[1419770941003000,1234]]}]'

    # List points
    curl -G 'http://localhost:8086/db/test/series?u=root&p=root&time_precision=u' --data-urlencode 'q=select * from ts'
    [{"name":"ts","columns":["time","sequence_number","value"],"points":[[1419770941003000,10001,1234]]}]

The following query returns an empty array in v0.8.5 and v0.8.8 on Mac OS X 10.10.1, whereas in v0.8.3 on Ubuntu 14.04.1 LTS a `Couldn't look up columns error` is returned:

    curl -G 'http://localhost:8086/db/test/series?u=root&p=root&time_precision=u' --data-urlencode 'q=select * from ts where time = 1419770941003000 and sequence_number = 10001'
    []

Furthermore when trying to delete a single point an error is returned too (v0.8.3, v0.8.3 and v0.8.8):

    curl -G 'http://localhost:8086/db/test/series?u=root&p=root&time_precision=u' --data-urlencode 'q=delete from ts where time = 1419770941003000 and sequence_number = 10001'
    Delete queries can't have where clause that don't reference time

**Comment by joel-airspring** [comment]
@vforgione 
In order to select a specific point, you have to give the timestamp at microsecond precision.  Influfxdb queries return the timestamp at millisecond precision by default.  (I'm in 0.8.8)  Change your general query to this:
`curl -G "http://example.com:8086/db/influxdb/series?u=root&p=root&pretty=true&time_precision=u" --data-urlencode "q=select * from 1d.percentile.top_tenth.example"`
to get the timestamp with the right precision.

Then, perform your specific query like so:
`curl -G "http://example.com:8086/db/influxdb/series?u=root&p=root&pretty=true" --data-urlencode "q=select * from 1d.percentile.top_tenth.example where time = 1420329600000###u and sequence_number = 1"`
where '###' is the last three digits of your microsecond-precision timestamp.  Don't forget the 'u'!
