### ISSUE TITLE
Create binary protocol API

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#139]
Should be a new thing under src/api that listens on a different port than anything currently running. Look into supporting the MySQL binary protocol as in the discussion here:

https://groups.google.com/forum/#!topic/influxdb/L9oVTwEizC4

Don't worry about `insert into` queries for now. All inserts should be through the prepared statement style that the thread talks about. Keep the statement ids 1-20 as reserved so we can support different binary encoding formats (like Protobuf, BSON, MessagePack).

**Comment by pauldix** [comment]
I'm closing this out for now. With the new line protocol (#2696) this is much less necessary. HTTP + Gzip and using the line protocol can already saturate what our storage engine can currently do.

Will open this up again at a much later date if there seems to be a big win from it.

**Comment by bobobo1618** [comment]
I know this is a very old bug but I have a use-case that isn't well satisfied by the line protocol + HTTP: Collecting metrics from low-power embedded devices.

HTTP and the text protocol are quite burdensome in resource-constrained environments like this. For example I'm using an ESP32 to push data from some attached sensors into InfluxDB and even just adding an `<sstream>` include costs 100KB, which was enough to push my binary over the size limit. Yes, the line-based format can be built other ways (like a ton of `sprintf`) but they become annoyingly complicated pretty quickly.

There's also the size issue. Every byte counts on a low power device because every byte means having the modem powered on just that little bit longer. The text-based format drastically increases the amount of data that has to be sent so the amount of time/power that has to be spent on transmission. A 4-byte float easily doubles in size when converted to text.

In my ideal world, there'd be a way to define a schema for what ends up basically being a plain struct. That way an embedded device can essentially just `memcpy` it over the network into InfluxDB.

I know this might not be a use-case you have any plan to support directly (there's always the MQTT feature built into Telegraf) but thought I'd raise it here anyway since it wasn't mentioned.
