### ISSUE TITLE
Add where against a regex to query language

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1430]
The query language needs to support queries like this:

```sql
SELECT mean(value)
FROM cpu
WHERE host =~ /some regex/
GROUP BY time(5m)

-- and the inverse
SELECT mean(value)
FROM cpu
WHERE host !~ /some regex/
GROUP BY time(5m)

-- or ignore case
SELECT mean(value)
FROM cpu
WHERE host =~ /some regex/i
GROUP BY time(5m)
```

Update the query language to be able to handle this and parse the regex

**Comment by dgnorton** [comment]
@benbjohnson @pauldix 

- https://github.com/influxdb/influxdb/blob/master/influxql/token.go#L39  comment says `!=` but scanner looks for `<>`.  Which is correct?

- If `<>` is correct, do we want to use `<>~` for regexp?  Feels awkward to me.

- Would it be better to make the regexp a string like `WHERE host =~ 'some regex'` instead of using the '/' delimiters?

- For the insensitive flag, can we just let that be handled by Go's regexp syntax?  e.g., `WHERE host =~ '(?i)rest of regexp'`  https://code.google.com/p/re2/wiki/Syntax

**Comment by pauldix** [comment]
Personally, I'd like it if we also supported `!=` for NEQ. And for the regex, `!~` feels right. As for having it be a slash vs. a string, I'd prefer slash, but if it's super tricky then I'm fine with using a string.

For the insensitive flag, is re2 what Go uses under the hood for regular expressions? If so, I'm fine with just using that too.

**Comment by dgnorton** [comment]
Can I take out support for `<>` so we don't have two syntaxes for the same semantic?  I'm in favor of making queries look the same everywhere.

I'll look at switching to slash for the delimiters.

Yes, Go uses re2.

**Comment by otoolep** [comment]
+1 on keeping queries look the same.

**Comment by pauldix** [comment]
SQL uses `<>` for NEQ, but I always hated that since most programming languages use '!='. And I think `<>~' for NEQ regex is really ugly. I vote supporting `<>` and `!=` and have `!~` for regexes. But that's my preference.

The regex thing doesn't have an equivalent in SQL, unless we support `LIKE` queries. But that's not exactly regex matching, which is easy for us to implement. So we don't have to deal with the baggage of SQL on those. Supporting `<>` would only be to ease the SQL people into our camp.

**Comment by dgnorton** [comment]
Okay, I'll leave `<>` in.  Maybe when we write `influxql fmt` it can rewrite with `!=`.   :-)
