### ISSUE TITLE
selecting a specific point - question/problem

### ISSUE THREAD

**Issue by jmccormick2001** [influxdb/influxdb#1492]
Hi,

I need to select a specific point, I'm running 0.8.8 version.  

Using the web interface I enter a query like this:
select * from hcdbstatus limit 1

I get a result back as I would expect.  I copy and paste the returned time/sequence values
into this query:

select * from hcdbstatus where time = 1422973421338 and sequence_number = 440001

But I get no rows back.  I thought this was possible by reading the query docs.
any help would be appreciated, thanks.

**Comment by joel-airspring** [comment]
Just ran into this myself in 0.8.8.  There's some inconsistency here between the docs and the product.  I've discovered that, when using curl, the query works if you add 'ms' to the timestamp like:

`select * from hcdbstatus where time = 1422973421338ms and sequence_number = 440001`

However, even though I can make the query work in curl, it still won't work for me in the web interface.

Here's the documentation that shows a query without 'ms' or any other time precision:  http://influxdb.com/docs/v0.8/api/query_language.html#selecting-a-specific-point

**Comment by joel-airspring** [comment]
Mystery solved.  The query I gave above ('time = 1422973421338ms') won't work.  I was confused because that query returns results via curl, although they were stunted -- timestamp and sequence_number only -- very weird.

Here's what's actually going on: the web ui returns data points with the default time precision of ms.  However, your data points are actually stored with microsecond precision.    So, you can't use the timestamp returned from the web ui because the query for a specific point must use the 'exact microsecond scale epoch', as the documentation says.  The time part of the correct query is
`time = 1422973421338###u`
where '###' are the last three digits of the timestamp in microseconds.

1400000000000 --> 1.4 trillion --> milliseconds
1400000000000000 --> 1.4 quadrillion --> microseconds
