### ISSUE TITLE
Fanout continuous queries failed while using group by

### ISSUE THREAD

**Issue by airywenter** [influxdb/influxdb#1522]
In stats, there are columns named   container_name,cpu_usage, and so on.
I write the sql:

" select DERIVATIVE(cpu_usage)  from stats group by time(10s)  into cpu.container.[container_name]  "

but it doesn't work .

thanks.

**Comment by pauldix** [comment]
You have to either group by the container_name or select the container_name otherwise, this query makes no sense. Also, if you have a group by time, it's not a fanout query, but an aggregate query, which means you'd need the container name in the group by statement.

Also, there are some known issues with derivative. I'm closing this for now as it will be fixed in the 0.9.0 release. Please wait for that.
