### ISSUE TITLE
end points versioning

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#1616]
I am trying to use 0.9 (am writing a Pandas dataframe wrapper for my evaluation) and [noticed](http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html) the end point is `/write` without any api version number, it is common to instead make it something like '/v1/write' and then later just bump the version.

**Comment by pauldix** [comment]
So far we haven't been doing versioning on the API endpoints side because it hasn't been possible to run two versions in parallel. This is probably going to continue to be the case. What's your goal with having the version in the path? Just that the client throws an error if you're running the wrong one?

**Comment by corylanou** [comment]
I've typically seen the `/v1/write` in a public consumption api, like say google maps, adwords, etc.  You don't typically see this on a server that you run in house (or privately hosted).  The reason being is that you have to know what version you are running regardless as you are spinning up the servers, so it falls under the end users control.  I'm not sure I see the use case where adding versioning to the server actually solves a problem.

**Comment by otoolep** [comment]
Agreed. This only makes sense to me in the context of something like a SaaS platform.

**Comment by dashesy** [comment]
The reason API endpoint versioning is important is that sometimes it takes time to update the consumer (e.g. for an app to go to app store, and then be updated by user). BTW, If I am not mistaken influxdb.com does offer hosting service, and with implementation of tags there will be more demand, I for one think it is now a very compelling solution for IoT.

**Comment by corylanou** [comment]
In general, the way our system works, if we upgraded an endpoint that was incompatible with a previous endpoint, it's likely the old endpoint would be usable either.  Considering that we have really only 2 endpoints (`/write` and `/query`) this doesn't fit well for our product.

I am very familiar with the concept that you are detailing out, but our product doesn't fit that style of IoT.  If you look at other databases out there, you will see that they don't support it either.  This is likely due to the complexity of how the endpoints have to interact with the underlying architecture.

**Comment by dashesy** [comment]
Makes sense, I plan to use it in the context of servers anyways, so the issue is resolved, thanks.
