### ISSUE TITLE
inconsistent quote handling in rc4 (and newer)

### ISSUE THREAD

**Issue by hawson** [influxdb/influxdb#1757]
Quote handling seems...odd in both the CLI `influx` program and the web admin interface.

Using double quotes returns zero results:

    show series where host="hostname"

Using single quotes returns the expected list of series:

    show series where host='hostname'

**Comment by dgnorton** [comment]
This is the expected behavior.  http://influxdb.com/docs/v0.9/query_language/querying_data.html#the-where-clause

Always use single quotes for string literals.  Tag values being the most common case.

Use double quotes (when needed) for db names, retention policy names, measurement names, and tag keys.

A detailed spec for the query syntax is available here... https://github.com/influxdb/influxdb/blob/master/influxql/INFLUXQL.md

**Comment by hawson** [comment]
Is there a reason why they are treated differently?

In many languages, there *is* a reason:  double quotes do variable interpolation, whereas single quotes do not.  In either case, quoting a static string (without variables) with either single or double quotes produces the same result.

Influxql, as a language, doens't appear to have variables, so handling them differently in *different places* strikes me as confusing.  Having this work:

    SELECT * FROM events WHERE state = 'NY';

but this fail:

    SELECT * FROM events WHERE state = "NY";

Is very much not "familiar to those coming from other SQL or SQL-like environments," where either quote is typically acceptable.

**Comment by dgnorton** [comment]
They are different things and it makes it much easier for the parser to distinguish between them.  It also makes queries easier to read / understand once you get use to it.  For example, if either type of quote were permitted and you came across someone else's query that looked like `SELECT value FROM cpu WHERE "foo" = "bar"`, is that comparing two string literals?  Values of two different tags?  The value of a tag to a string literal?  You'd have to examine the database further to figure it out.  The parser wouldn't be able to tell either and would have to pass it on to the engine.  The engine, before treating anything like a string literal, would have to look to see if it existed as a tag key, retention policy, etc. first.  Then what happens if it gets added as a tag key or retention policy later?

The way to remember which to use in InfluxQL:

Identifiers are either unquoted or double quoted.  Identifiers are db names, retention policies, measurements, or tag keys.

String literals are always single quoted.
