### ISSUE TITLE
Add support for 'having' queries

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#183]
Should we support `having` in queries? Like this:

```sql
select count(value) from some_series
group by time(5m)
having count(value) > 23
```

**Comment by RubenDZ** [comment]
+1

**Comment by coudel** [comment]
+1, this can be avoided by creating a continious query which not seems to be a dificult solution.

**Comment by sc0rp10** [comment]
+1

**Comment by cdimitrov** [comment]
+1

**Comment by abeninskibede** [comment]
+1

**Comment by nelcy** [comment]
+1

**Comment by jpbetz** [comment]
+1

**Comment by zapient** [comment]
+1

Any news on this feature?

**Comment by ollijm** [comment]
+1

This would be very much needed.

**Comment by faxm0dem** [comment]
:+1: this would be extremely useful!

**Comment by ericx10ng** [comment]
How's going on?

**Comment by cmben** [comment]
+1

**Comment by ram-nadella** [comment]
Hi @pauldix, any update on the status of the `having` feature?

I noticed you and @chobie had a discussion in the pull request, but it is not clear whether the feature has made it in and if not, do you have any estimate of when it would be available?

The use case you mention in one of your comments at the top of this thread is very powerful and necessary for exploring time series data – how the top n items instead of top 10 values for every item.

**Comment by kbespalov** [comment]
+1

**Comment by TechBK** [comment]
+1

**Comment by reinhard-brandstaedter** [comment]
+2

**Comment by ScottStevenson** [comment]
+1

**Comment by mpicaud** [comment]
+1

**Comment by nilliams** [comment]
+1 

On my first foray with Influx and very quickly ran into multiple cases where I need this kind of behaviour. How are people working round this currently, with CQs?

**Comment by Apollon77** [comment]
+1

**Comment by jholovacs** [comment]
+1

**Comment by scotloach** [comment]
+1
I need this.  Need to exclude certain values in a continuous query and can't find another way to do it.

**Comment by lambdaq** [comment]
+1 please support `HAVING` clause

I encountered another issue in Grafana https://github.com/grafana/grafana/issues/4623

The problem is Grafana displays all `GROUP BY` results, lots of zeros can not be hidden.

We hope Influxdb can filter those zeros out, the best method so far is to have a `GROUP BY ... HAVING` clause.

**Comment by shimonm** [comment]
+1

**Comment by langjiyutao** [comment]
+1

**Comment by ChenWenBrian** [comment]
+2019

**Comment by gliu93** [comment]
+2020

**Comment by javierbarboza** [comment]
+2021

**Comment by psihonavt** [comment]
+1

**Comment by UP929312** [comment]
+1

**Comment by SpaceAzur** [comment]
+1

**Comment by sanderson** [comment]
With the introduction of InfluxDB 3.0 and SQL support, `HAVING` queries [are available](https://docs.influxdata.com/influxdb/cloud-serverless/reference/sql/having/). You can currently use them in [InfluxDB Cloud Serverless](https://www.influxdata.com/products/influxdb-cloud/serverless/), [InfluxDB Cloud Dedicated](https://www.influxdata.com/products/influxdb-cloud/dedicated/), and-soon-to be released InfluxDB Clustered. SQL support will also release with InfluxDB OSS 3.0 in the near future.

I may be wrong, but I don't really see `HAVING` support being added to InfluxQL.
