### ISSUE TITLE
Wire up COUNT DISTINCT aggregate

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1891]
From a syntax perspective it should look like this:

```sql
select count(distinct id) from events
```

The underlying implementation should use the DISTINCT Map function, but have a new reducer that combines the Map output and outputs a count.

**Comment by pauldix** [comment]
I should mention that the target could be either a field or a tag key. The implementation would be different depending on which type was passed in.

**Comment by corylanou** [comment]
Is it more common to see this:

```sql
select COUNT(DISTINCT id) as count FROM events
```

**Comment by beckettsean** [comment]
I think COUNT_DISTINCT will lead to less short-term frustration and confusion than COUNT(DISTINCT).

Given that we won't support any other nested aggregates right now I think this should be defined as a new aggregate. Any examples that show COUNT(DISTINCT) will give the impression that aggregations can be nested, at least inside a COUNT. I can easily imagine running COUNT(SUM) ... as a quick way of verifying how many buckets my GROUP BY will return rather than trying to parse the JSON return. Since that won't work I think we should use count_distinct, which gives me much less reason to believe something like count_sum would work. 

Using COUNT(DISTINCT) does mirror other SQL implementations, but our COUNT function does not, as it can't nest anything else. Why mirror the syntax when the underlying behavior is not similar?

**Comment by pauldix** [comment]
@beckettsean `derivative` will actually use the nested syntax. We should just be validating it if they do a nesting that we don't support. See #1477

**Comment by pauldix** [comment]
@corylanou agreed on your syntax, updated the issue to reflect that

**Comment by corylanou** [comment]
This issue depends on https://github.com/influxdb/influxdb/issues/1815 being done first.
