### ISSUE TITLE
Use GROUP BY value in WHERE

### ISSUE THREAD

**Issue by jd** [influxdb/influxdb#1973]
That may be a documentation issue (I wish), but I am not able to achieve what I want in a query.

I want to:
1. Run aggregate over points with GROUP BY time(5m)
2. Only get the result for the group of 5 minute between 12:00 and 12:58

The obvious way to do that is to run:
```
SELECT mean(value) FROM myserie WHERE time > '12:00' AND TIME < '12:58' GROUP BY time(5m)
```

Except that this is not what I want. I don't want to limit the points used by the aggregate to the ones between 12:00 and 12:59. I want to InfluxDB to returns me the last 12:55 aggregate with all the points until 13:00 aggregated, I don't want it to drop 2 minutes of points in the last aggregate.

**Comment by beckettsean** [comment]
@jd I'm confused by your setup. I think what you want is the MEAN aggregation in 5 minute buckets for all points from 12:00 to 13:00. Why then are you using 12:58? If you want all points up to 13:00 and you want 5 minute buckets, I can't see a reason to stop the grouping at 12:58.

Why doesn't this query satisfy your needs?
```
SELECT mean(value) FROM myserie WHERE time > '12:00' AND TIME < '13:00' GROUP BY time(5m)
```
Does that not return 5 minute buckets of the MEAN between noon and 1 p.m.?

**Comment by jd** [comment]
@beckettsean I don't want to have to compute the boundaries manually before doing a request. So yes your query does satisfy my needs, but I wish InfluxDB would allow to do that without having to compute 13:00 myself. :)

**Comment by beckettsean** [comment]
@jd I think this comes down to the principle of least surprise. Given this query:
```
SELECT mean(value) FROM myserie WHERE time > '12:00' AND TIME < '12:58' GROUP BY time(5m)
```
One reasonable person might assume that they would get back 11 buckets, one each for 12:00, 12:05, ... up to 12:50 but without a 12:55 bucket, since the end of the bucket falls outside the time range. Another reasonable person might assume that they would get back 12 buckets, one each for 12:00, 12:05, ... up to 12:55 but with only four minutes of time in the last bucket, since the time range excludes the final minute. A third reasonable person might assume that they would get back 12 buckets, one each for 12:00, 12:05, ... up to 12:55 with each bucket being a full five minutes, since the GROUP BY specified 5 minute buckets.

To avoid violating the principle of least surprise where there's no clear precedent or expectation, and in this case I would say all three interpretations are fairly equally reasonable, I believe the system should make as few inferences and interpretations as possible. Therefore, create buckets of five minutes and fill them with the points between 12:00 and 12:58. The points in 12:59 were excluded in the WHERE clause so we exclude them. To include them would be to infer that the GROUP BY clause has precedence over the WHERE clause. The question of whether the final bucket is 5 minutes with a missing minute of data or is a 4 minute bucket is, I think, semantic and irrelevant.

**Comment by jd** [comment]
I don't think it's fair to close this bug. I'm not saying that the current behaviour is wrong.
You can consider this is a feature request.

**Comment by beckettsean** [comment]
Feature requests that aren't on the current roadmap are closed to keep the open issues to a minimum. I've added the RFC tag so the community can weigh in. Should there be interest we are happy to re-open the issue.
