### ISSUE TITLE
Server crash when looking up a data point by a specific time

### ISSUE THREAD

**Issue by robbyt** [influxdb/influxdb#2002]
The following query causes influxdb 0.9 rc14 to crash- seems to be caused by the single quotes

`select * from data where time = '2015-03-18T04:30:38.666604Z'`

Stack trace:
https://gist.github.com/robbyt/4e0007efe29c0386e1b7

**Comment by pauldix** [comment]
I don't think this is due to the quotes, but due to either no results getting returned by the query or that the single result it finds doesn't work. Either way it's something we should track down.

Some good tests to write against this:
* no data matching
* the from measurement has one series and has a point that matches
* the from measurement has multiple series (has tags) with one point matching
* the from measurement has multiple series (has tags) with two or more points matching

**Comment by knabben** [comment]
Updates on this?

**Comment by CDA0** [comment]
is the same error caused when a time range is given?  ie where time > '2014-08-01T11:50:00Z' and time < '2014-08-01T13:45:00Z'

**Comment by toddboom** [comment]
Just tested this on pre-RC30 and this appears to be fixed.
