### ISSUE TITLE
2 points with same time overwritten?

### ISSUE THREAD

**Issue by sammy007** [influxdb/influxdb#2055]
I have distributed app pushing points every minute to avoid thousands of writes once a minute. Points are reduced on app side, then every minute they are going to influxdb. If I pushing 2 points with 1 minute precision to database there will be 1 point actually. Is it expected behaviour? Any design suggestion if so?

**Comment by pauldix** [comment]
Points in a series can not have the same exact time (down to nanosecond). A series is defined by the measurement and tagset. In a typical database you'd have thousands to millions of unique series.

If you only care about minute level precision, you can use the lower order bits to have multiple data points with the same minute timestamp. With that you can have 60 billion points in the same minute in the same series.

This is by design since no one that we know of cares about nanoseconds. Thus they can have many data points all with the same "timestamp"

**Comment by sammy007** [comment]
> If you only care about minute level precision, you can use the lower order bits to have multiple data points with the same minute timestamp.

Low order bits? Could you post 2 points for example please? Not sure I understood correctly. Does it mean that I should use "ms" precision actually in database and don't care because there will be a few writes anyway because data already aggregated? Thanks.
