### ISSUE TITLE
Re-work Graphite input and metric processing

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#2102]
Our Graphite support doesn't work they way we had hoped. We made some assumptions about the format of the metrics coming in which don't actually hold up. For example, we assumed all metric names would be of this form:

`cpu.region.us-west.hostname.server01`

where the measurement name is the first (or last) and is accompanied by an even number of delimited fields.

This is not the case. Here is an example of the collectd output, with the Carbon write pluging enabled, from a Ubuntu 14.04 server:

```
fisher.df-root.df_complex-reserved 1949122560.000000 1427498397
fisher.df-root.df_complex-used 2705641472.000000 1427498397
fisher.memory.memory-used 340230144.000000 1427498397
fisher.memory.memory-buffered 179859456.000000 1427498397
fisher.memory.memory-cached 353742848.000000 1427498397
fisher.memory.memory-free 162619392.000000 1427498397
fisher.load.load.shortterm 0.000000 1427498397
fisher.load.load.midterm 0.010000 1427498397
fisher.load.load.longterm 0.050000 1427498397
fisher.interface-eth0.if_octets.rx 553.888478 1427498397
fisher.interface-eth0.if_octets.tx 2784.150049 1427498397
fisher.interface-eth0.if_packets.rx 8.204268 1427498397
fisher.interface-eth0.if_packets.tx 4.002082 1427498397
fisher.interface-eth0.if_errors.rx 0.000000 1427498397
fisher.interface-eth0.if_errors.tx 0.000000 1427498397
fisher.interface-eth1.if_octets.rx 0.000000 1427498397
fisher.interface-eth1.if_octets.tx 0.000000 1427498397
fisher.interface-eth1.if_packets.rx 0.000000 1427498397
fisher.interface-eth1.if_packets.tx 0.000000 1427498397
fisher.interface-eth1.if_errors.rx 0.000000 1427498397
fisher.interface-eth1.if_errors.tx 0.000000 1427498397
fisher.interface-lo.if_octets.rx 1997.538536 1427498397
fisher.interface-lo.if_octets.tx 1997.538536 1427498397
fisher.interface-lo.if_packets.rx 17.108894 1427498397
fisher.interface-lo.if_packets.tx 17.108894 1427498397
fisher.interface-lo.if_errors.rx 0.000000 1427498397
fisher.interface-lo.if_errors.tx 0.000000 1427498397
fisher.irq.irq-0 0.000000 1427498397
fisher.irq.irq-1 0.000000 1427498397
fisher.irq.irq-6 0.000000 1427498397
```

One possible way to support these variable naming schemes is to allow our users to input regexes, or other simplified parsing rules, either in the config file, or dynamically at the CLI. These rules would mark the various delimited parts of the metrics as tags, fields, and measurement names. Without this the best the system can offer is to take the whole metric name, use that as the measurement name, and not perform any tagging.

**Comment by corylanou** [comment]
My understanding after seeing it is that it is very unlikely there are actual "tags" to be parsed from the measurement name, and it's more likely they just expect to see the measurement names.  It's probably easier to allow them to query the measurements via regex than to parse and tag via regex.

**Comment by otoolep** [comment]
You could be right @corylanou -- but in the example above, hostname is always the first field. While the other fields could be highly variable, some fields could be fixed. So it could be very useful to some people to be able to tell InfluxDB that "strip the first field and use its value as a tag for the key host. Use the rest as the measurement name".

**Comment by otoolep** [comment]
One could imagine a regex rule like this:

```
(?P<host>.+).(?P<region>.+).(?P<measurement>.*)
```
which would mean take the first field and tag it as 'host', take the second and tag it as 'region', and use the rest as the measurement name. You get the idea.

**Comment by Civil** [comment]
In the example above it is, but you know, collectd is NOT THE ONLY way to send metrics to graphite. You can't relay that first field will be a host name, you can't relay that there'll be regions, that measurement will be only one filed, etc., you basically can't relay on anything.

**Comment by pauldix** [comment]
@corylanou people case just send stuff in and have them be the measurement names, but the experience will be very poor. They'll basically lose much of the capability of Influx if they can't tag advantage of the tags.

Also, querying against regexes on measurements falls over when you get over 100k or so. This is one of the big reasons we moved over to using tags in the first place. So we could create an inverted index and get greater performance.

I like @otoolep's method of parsing out names. You could give them an easier format without using regexes since graphite always uses `.` for delimiters. Just do something like a string:

```
:hostname.:region.:measurement*
```

@Civil if they have different collectors or sources sending stuff via the graphite protocol, the way to deal with it is to run multiple Graphite ports on Influx and have each one have a different configuration for parsing the names.

**Comment by corylanou** [comment]
@pauldix that makes sense, and should be pretty easy/quick to implement.

To be clear, this is still not so much a "regex" as it is a template, so to be specific, it would be something like:

```
<tagname><delimiter>:<tagname><delimiter>:<measurement>*
```

So that something like this:

```
fisher.memory.memory-free
```

could be converted to 

```
tags: {"host":"fisher","metric_name":"memory"}
measurement: "memory-free"
```

with the following template expression:

```
host.:metric_name.:measurement*
```

I don't think we need to start/end with a `:`. We might also need a way to specify what our delimiter is, in case they are using `:` in their metric names already.

It will also force `measurement*` to become a bit of a reserved word in the template processing, but I'm ok with that as well.

Thoughts?

**Comment by otoolep** [comment]
Yes, a template works just as well. The use of regex was just to get the idea across -- a simplified template would be best.

@corylanou -- I actually think using `:` at the start of a template keyword is helpful, as it makes it clear to the next guy that it's replaced -- look the Go convention for HTTP muxers, and Ruby. Using `:` might also mean that `measurement` is not a reserved word, only `:measurement`.

**Comment by otoolep** [comment]
To be clear, my goal is here is not design something comprehensive -- that would be a big job -- but to have InfluxDB be able support the basic cases. There is a lot of low-hanging Graphite metrics out there we can't current process.

**Comment by pauldix** [comment]
@corylanou they can't use `:` in graphite metric names. The reason I had that there is because there could be parts of the name they simply want to match against and ignore. That would be a string without the leading `:`. Another thing that they could do would be to put a `*` in that spot to simply match against any string and ignore it.

I meant for `:measurement*` to specify that the remaining portion of the graphite name maps to the InfluxDB measurement name. Might be better to just use a special character for this without the `:measurement`. Maybe `$` for the measurement name? And a trailing `*` on that would indicate that everything after goes with that.

**Comment by thuck** [comment]
@otoolep can't this be implemented using grok expressions? It works very well for logstash.
For example a quick expression that matches all the cases above would be:
`^%{DATA:hostname}\.%{DATA:interface}\.%{DATA:metric_name}(\.%{DATA:type})? %{DATA:value} %{DATA:time}$`
The result will be a dictonary/json so it matches very well the concept of tags.

**Comment by otoolep** [comment]
In principle yes, but grok is not written in Go, and we want to stick with
a pure Go build.

**Comment by corylanou** [comment]
We also want to have something that is super performant, so we may come up with a basic template that we don't even need regex to parse it with.

**Comment by thuck** [comment]
Okay; but any chance of this reaching the 0.9.0 version so we can use this together with collectd in production?

**Comment by corylanou** [comment]
I will try to get to this shortly as I know a lot of people are waiting on it.

**Comment by MrEnzyme** [comment]
I don't think having multiple ports open for different kinds of metrics is a good plan, because in the case where you have a relay distributing metrics across multiple nodes; you'd have to change the config in 2 places (influx and the relay) instead of just one. Ideally you could define multiple metric templates and then use pattern matching or something to determine which template to use.

**Comment by damm** [comment]
I would suspect the tag name that will be selected by most users; will not be set by them.  Depending on how you configure Collectd/Diamond/etc the prefix turns into the tag.

So when you write

`servers.example-ubuntu-1404.loadavg.01` it should turn into 

```
tags: {"host":"example-ubuntu-1404","metric_name":"loadavg"}  
measurement: "01"
```

is what your saying?

**Comment by damm** [comment]
This was interesting; I actually answered this by installing rc18.

`servers.desolation.loadavg.01` got lost; using Grafana 2 I could find the servers tag but there was nothing else to select afterwards.

If I dropped the prefix of servers I suspect this would work right.

I think I also should set `name-separator` to be a "." in this case? am I wrong?

**Comment by benjarrell** [comment]
Using Diamond outputting graphite to InfluxDB v0.9.0-rc19 graphite input the data is tagged automatically. I left `name-separator` commented out.

I can't use Diamond's InfluxDB output since RHEL6 uses python 2.6, which [influxdb/influxdb-python](https://github.com/influxdb/influxdb-python) does not support.

With just the default collectors I am seeing these errors:

```
[graphite] 2015/04/06 12:46:15 unable to parse data: received "servers.test02.vmstat.pswpout" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:15 unable to parse data: received "servers.test02.vmstat.pgpgin" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:15 unable to parse data: received "servers.test02.vmstat.pgpgout" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:15 unable to parse data: received "servers.test02.vmstat.pswpin" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.MemTotal" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.MemFree" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.Buffers" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.Cached" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.SwapCached" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.Active" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.Inactive" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.SwapTotal" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.SwapFree" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.Dirty" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.Shmem" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.Committed_AS" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.VmallocTotal" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.VmallocUsed" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:18 unable to parse data: received "servers.test02.memory.VmallocChunk" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:19 unable to parse data: received "servers.test02.loadavg.01" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:19 unable to parse data: received "servers.test02.loadavg.05" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:19 unable to parse data: received "servers.test02.loadavg.15" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:19 unable to parse data: received "servers.test02.loadavg.processes_running" which doesn't conform to format of key.value.key.value.name or name
[graphite] 2015/04/06 12:46:19 unable to parse data: received "servers.test02.loadavg.processes_total" which doesn't conform to format of key.value.key.value.name or name
```

Which of course means those values are not recorded.

**Comment by damm** [comment]
@benjarrell if you drop the prefix and put the metrics in the root; it should pick them up.

**Comment by damm** [comment]
@corylanou how can we work around prefix's like that with tagging short of dropping everything to the root? (as we know that works for me at least)

**Comment by corylanou** [comment]
I think the answer is for us to rework this to use a template as described above.  I'll see if I can get this prioritized.  It should be fairly simple to change.

**Comment by arnoldschik** [comment]
@corylanou i tried to feed data into influxdb using the graphite input as well and noticed that the expected precision is in epoch microseconds but most of my datasources deliver metrics in second precision, I think it would be helpful to be able to configure the precision in the graphite config section.

**Comment by cannium** [comment]
In my opinion, the point here is the metric name graphite sends is hierarchical,  while influxdb expects a structured key-value metadata. For example, I got `servers.localhost.cpu.cpu0.irq` from diamond, and by default influxdb parses it into:
```
{
name: "irq",
tags: {
  "servers": "localhost",
  "cpu": "cpu0"
}}
```
(Forgive me about the indentation here)
But I think a better result could be:
```
{
name: "cpu.irq",
tags: {
  "servers": "localhost",
  "device": "cpu0"
}}
```
or
```
{
name: "cpu",
tags: {
  "servers": "localhost",
  "device": "cpu0",
  "measure": "irq"
}}
```
which I think requires more changes to diamond than to influxdb because influxdb can only handle those names case by case if we don't touch diamond.
As I figured out, diamond's full name structure is `<prefix><hostname>[suffix]<path><metric name>`(and collectd is similar, `<prefix><hostname><suffix><plugin><type><name>`). And the above example is structured as:
```
prefix: servers
hostname: localhost
path: cpu
metric name: cpu0.irq
```
So you see if the metric name is `irq.cpu0` instead, it would be easier to parse, as `<prefix><hostname><metric name><measure>[device]`. The `[device]` part is optional because names like `servers.localhost.memory.Active` and `servers.desolation.loadavg.01` don't have it. You don't put an optional section in the middle for parsing.
I'll try to propose this change to the diamond community and see what they think.

**Comment by damm** [comment]
This really should have been a blocker before 0.9.0 was released; as using Diamond ..

I use Sensu as well as Diamond to write metrics to influxdb :(

**Comment by labrown** [comment]
The real problem is that many people use Graphite and send metrics to it using any old naming scheme they come up with. Collectd/statsd/diamond is just one way to get that done.  We have data being fed to graphite using plain old shell scripts and netcat calls, for example.  Any general solution to this is going to have to be very flexible.

**Comment by bmhatfield** [comment]
+1 to @labrown - we have metrics compiled, sometimes dynamically, from a variety of sources. Arbitrary, schema-less metric naming is a *strength* for us, and we hope to continue to use it. Perhaps considering tags as just "tag" without "key=value" would work here?

**Comment by pauldix** [comment]
We're totally open to suggestions on this. We'd like to make sure people switching from Graphite are happy. The conversion into the tag scheme is tricky, so more people putting up their actual schemas would help.

Ideally, people will be updating to use the new line protocol and take advantage of the structure that InfluxDB provides.

**Comment by labrown** [comment]
I'm going to pile on here:  That vaunted line protocol might as well not exist until we have solid documentation for it.

**Comment by beckettsean** [comment]
@labrown totally understand your frustrations. We're working hard to get the docs updated but decided not to hold up the release of the db just because the docs are lagging a bit.

At least there aren't any lies about the line protocol in the docs, which is more than can be said for some of the pages.

**Comment by richardelling** [comment]
Would it hurt to have another graphite ingestor where the graphite metrics are assigned to enumerated keys?
For example,

> something.somehost.athing.anotherthing.metric

becomes

> metric, key1=something, key2=somehost, key3=athing, key4=anotherthing

admittedly, this is butugly, but...

Folks moving from more restricted environments, like collectd, where the limited number of key=values already fights with graphite's hierarchy might also find this to be a reasonable stop-gap until the new influxdb line protocol is soaked.

**Comment by cdgraff** [comment]
I think is really good approach defined here: http://metrics20.org/ about how metrics need to be... but I'm Collectd/Graphite users, and today my main priority is try to migrate to Influxdb but using the same Shippers. (Diamond, Collectd and Metrics from Codahale) without full compatibilty with current shippers is imposible to made the switch.

**Comment by otoolep** [comment]
@jwilder is taking a look at this, and plans a comprehensive solution for the next release.

**Comment by rmoff** [comment]
Just want to chuck my tuppence-worth in here. I started looking at InfluxDB in the .8 release and loved it because it was a drop-in replacement for existing Graphite/Carbon. Being able to switch it in like that made it a no-brainer to evaluate ([and find to be awesome, and ditch graphite, yay](http://www.rittmanmead.com/2015/02/obiee-monitoring-and-diagnostics-with-influxdb-and-grafana/)). 
That this is broken 0.9.0 is a shame, but it's good to see it's under active consideration how to fix best. My layman's input would be : KISS. Experience from trying to integrate other toolsets is the higher the friction, even if the result is "better" / "cleaner" means that you actively set the bar higher for people to work with the tool. Sometimes that's necessary to retain the integrity of the tool, but sometimes not. 

@bmhatfield hit the nail on the head here: 
> Arbitrary, schema-less metric naming is a strength for us

I want to be able to chuck my metrics at a tool and have it store them. I don't want to have to worry about schemas/tags, and I don't want to have to write regex in order for the tool to accept my metrics, because I don't necessarily know what my metrics will look like. 

Maybe there needs to be a "kludgy" solution rather than/as well as a "perfect" solution for graphite/carbon input. Either that, or just drop support for carbon and tell people to use a better input option?

**Comment by MrEnzyme** [comment]
@rmoff +1
My situation (which is probably common) is that I don't have control over most of the metric names I send to Influx (they come from things like collectd and codahale) and I want to at least be able to just use the whole, ugly series name as is without changing anything on the metrics producing end. If there's a way to set up nicer tag parsing that will work with a variety of metric sources, great, but for a minimum it would be great to continue using Influx as a drop-in graphite replacement.

**Comment by joakimberglund** [comment]
@MrEnzyme +1
Exactly, we have a legacy installation that needs to work without rewriting everything...
The new schemas/tags solution is great but until we have moved away from using the Graphite protocol to native Influx, the graphite input needs to work as it did before... how ugly and bad it might be...

**Comment by Dieterbe** [comment]
as for metric organisation/tags, you might find some inspiration in the metrics2.0 tooling (structured metrics plugins, carbon-tagger), it is basically the same as what has been suggested here. unfortunately i'm also not aware of a *clean* solution for this messy problem, other than asking people to either submit tagged metrics (by including tag keys in the metric string such as the metrics2.0 extended graphite protocol, which a few small projects use, and hopefully will be adopted later by more tools), writing parsing regexes like in structured-metrics plugins, or just live with the key1/key2 style (which the metrics2.0 tools do as n1,n2,...)
i think tags and graphite's tree simply can't easily be reconciled.
influxdb supporting tags well is great, but deprecating support for untagged metrics basically means graphite can't be well supported.

**Comment by pauldix** [comment]
We'll be starting work on updating how we handle Graphite next week. One of the things we'll include is the ability to just pass through the graphite name as the InfluxDB measurement name. More on this next week.

**Comment by abhiofdoon** [comment]
Is this target for 0.9.1 ?

This blog release today mentions that we will have it in 0.9.1 release on 2nd July
https://influxdb.com/blog/2015/06/19/Announcing-Telegraf-a-metrics-collector-for-InfluxDB.html

However this issue is targeted for 0.9.2 ?

**Comment by beckettsean** [comment]
@abhiofdoon this issue has been assigned to the 0.9.1 release since Friday, June 12th. What makes you believe it's targeted for 0.9.2?

**Comment by abhiofdoon** [comment]
Never mind. I think I mis-read the target release in the comments above. My bad.
