### ISSUE TITLE
db url parameter to avoid {"error":"database is required"}

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#2127]
When writing data to `/write` can we have a url parameter similar to `/query` like `db=mydb` this way we can keep initial data as a fixture in a `.json` file (without `database` key) and use curl to push same data to a multiple databases without the need to use awk.

```
curl -XPOST 'http://localhost:8086/write' --data-binary "@initial.json" --data-urlencode "db=mydb"
```

**Comment by jimmystewpot** [comment]
This issue seems to be a regression. 
Previously in InfluxDB (versions prior to 0.9.0) it was possible to add data without the database key/value in the JSON. It seems that the administration UI still passes the db= field in the URI for the post. However the server rejects the JSON POST with a not very descriptive error message. The error that returns via the admin UI is just "Bad Request" without any descriptive terminology. 

Here is the server log
```
[http] 2015/05/15 03:04:30 127.0.0.1 - - [15/May/2015:03:04:30 +0000] POST /write?u=root&p=<password>&db=<db-name> HTTP/1.1 400 57 http://localhost:8083/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2311.135 Safari/537.36 1a98c6d8-faaf-11e4-9195-000000000000 2.123643ms
```
I can see that the status code is 400 which is correct for "Bad Request" as seen via the UI. However when I do a tcpdump against the session I can see that more descriptive data is returned. Yet it is not displayed. The error in the payload is.

```
{"error":"database is required"}
```

**Comment by beckettsean** [comment]
Given that the JSON protocol is deprecated, this is no longer relevant. The line protocol already requires the database to be specified in the GET query string.
