### ISSUE TITLE
feature to have retention policy based on reception time

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#2135]
Currently the retention policy keeps records based on event time, so `7d` means deleting all events that are older than `now()-7d`. Therefore we cannot use a short retention period to keep any historical data (as a temporary place for some intermediate results).
The feature I am asking here is to have an option to instead use the date a record is created/received, so `7d` would means deleting any record server received before current week (no matter what the actual timestamp of the point).
I faced this [issue](https://github.com/influxdb/influxdb/issues/2133) when I re-compiled some old data (using a process that now relies on InfluxDB), I saw the intermediate series (with short retention policy) was sometimes deleted almost as soon as it was created, thus not allowing the postponed process to handle it; historical data cannot be kept in a short retention policy.

**Comment by pauldix** [comment]
Because of how retention policies work, we won't be able to implement this as a feature. The only way for it to work would be for you to write the time as a different field and let Influx set the time the point is indexed by. But then you wouldn't be able to do a bunch of queries against it.

If this is for some fixup of historical data, the best thing for you to do is to modify the retention policy to have something much larger, write in the data, let the other processes handle it, then when everything is back to normal alter the retention policy to have the shorter period again.
