### ISSUE TITLE
Aggregation not working

### ISSUE THREAD

**Issue by zidekmat** [influxdb/influxdb#2308]
When I query SELECT value FROM "test"."ten_hours".CPU WHERE VM_ID='1'
I get this:
![screenshot_2015-04-16_10-38-12](https://cloud.githubusercontent.com/assets/3611530/7177185/df7e72b8-e424-11e4-8a38-3b6490ac2c50.png)

and when I query this: SELECT mean(value) FROM "test"."ten_hours".CPU WHERE VM_ID='1' GROUP BY time(1m)

I get:
![screenshot_2015-04-16_10-40-08](https://cloud.githubusercontent.com/assets/3611530/7177196/f88121ac-e424-11e4-834e-8f1b63946178.png)

which is probably not the right result or am I doing something wrong?

InfluxDB 0.9 rc24

**Comment by xetorthio** [comment]
I have observed the same thing. And this gets even weirder when you add a where condition on time, for example in my case I have only 1 points in the series ```foo```:

time | value
----- | -------
2015-04-15T13:27:46.672Z | 10

And my query is: ```select sum(value) from foo where time > now() - 2w group by time(1w)```, and I gets back:

time | sum
------ | ------
2015-04-02T00:00:00Z | null
2015-04-09T00:00:00Z | 10
2015-04-16T00:00:00Z | null

Beside the fact that it is returning 3 periods (seems like one before and one after) it is taking the beginning of the week (which is my group by period) differently than in influx 0.8, where beginning of the week was always Sunday

**Comment by fahadullah** [comment]
I am not sure if this is an expected behavior but I am seeing null values returned for time buckets where points are missing,

My time series has these points,

2015-04-24 00:53:30 +0000 UTC, 1
2015-04-24 00:53:40 +0000 UTC, 2
2015-04-24 00:53:55 +0000 UTC, 4
2015-04-24 00:54:00 +0000 UTC, 5
2015-04-24 00:54:05 +0000 UTC, 6
2015-04-24 00:54:15 +0000 UTC, 7

- This works as expected,

SELECT sum(value) FROM metric WHERE (time >= '2015-04-24T00:53:30Z' AND time < '2015-04-24T00:54:16Z') GROUP BY time(10s)

2015-04-24 00:53:30 +0000 UTC, 1
2015-04-24 00:53:40 +0000 UTC, 2
2015-04-24 00:53:50 +0000 UTC, 4
2015-04-24 00:54:00 +0000 UTC, 11
2015-04-24 00:54:10 +0000 UTC, 7

- Specifying a bigger time bound returns empty values,

SELECT sum(value) FROM metric WHERE (time >= '2015-04-24T00:53:20Z' AND time < '2015-04-24T00:54:26Z') GROUP BY time(10s)

2015-04-24 00:53:20 +0000 UTC, null
2015-04-24 00:53:30 +0000 UTC, 1
2015-04-24 00:53:40 +0000 UTC, 2
2015-04-24 00:53:50 +0000 UTC, 4
2015-04-24 00:54:00 +0000 UTC, 11
2015-04-24 00:54:10 +0000 UTC, 7
2015-04-24 00:54:20 +0000 UTC, null

Is this expected? I am using rc24.

**Comment by marcosnils** [comment]
@fahadullah you can use `fill(0)` at the end to return 0 for intervals that doesn't contain data

**Comment by fahadullah** [comment]
I would have preferred to not get any time buckets where points are missing. I haven't gone back and checked if this is how it worked with 0.8.8 or if this is only with 0.9.

**Comment by marcosnils** [comment]
@fahadullah this is how 0.9 works. Things have changed a lot from 0.8 to 0.9 even though it seems like a minor release :). 
You'll find  many things either work differently or are yet still to be polished, I can tell you that by experience :smile:

**Comment by otoolep** [comment]
Check out the docs - it can do what you want.

http://influxdb.com/docs/v0.9/query_language/querying_data.html#filling-intervals-with-no-data

Philip

**Comment by fahadullah** [comment]
Thanks. That's very helpful.

**Comment by zidekmat** [comment]
Great, I must have skipped that one. Thank you and sorry for an invalid issue.
