### ISSUE TITLE
v0.8.8 malformed JSON

### ISSUE THREAD

**Issue by kerush** [influxdb/influxdb#2321]
I'm trying to load the following:
```
[{"name":"engine","columns":["time","latency","key","payload"],"points":[[1429017531018030,3250,"LX_20641823",{"message_type": "oLX", "id": 20641823}],[1429017531018268,4430,"KO_20642312",{"message_type": "oKO", "id": 20642312}],[1429017531018268,4430,"KO_20642313",{"message_type": "oKO", "id": 20642313}]]}]
```
But I'm getting the below:
```
Unknown type map[string]interface {}
```
I think the JSON is valid, the whole request and the the "payload" field. Do you have any idea why this is failing? I can't find anything in the docs that refers to this type of problem.

**Comment by marcosnils** [comment]
@kerush I don't know your use case but influx doesn't know anything about JSON values in series. It's supposed to be used mainly for time series purposes such as counting and measuring data. If you necessarily need to save that type of structure in your series ( which I believe it's wrong by design) you could store it as a string and then do the marshal / unmarshalling from your app

**Comment by toddboom** [comment]
@kerush what @marcosnils said is correct - you'll need to handle marshaling and unmarshaling on your own.
