### ISSUE TITLE
Cannot query data that was written with non-default retention policy

### ISSUE THREAD

**Issue by dneuman64** [influxdb/influxdb#2424]
I am writing data to the database using the go client.  If I write the data with the default retention policy, I am able to query the data, if I write the data using a non-default retention policy I am not able to query the data.  This only seems to happen when also using tags.
Steps to reproduce:
create a database
create a retention policy
write data with at least one tag and the default retention policy
query that data - data should return
write data with at least one tag and a non-default retention policy
query that value, no data will return.

please let me know if you need more information.

**Comment by gunnaraasen** [comment]
Queries on non-default retention policies must specify the retention policy.  Otherwise, only the point written to the default retention policy will be returned.  Try a query like this,

```
SELECT * FROM "database_name"."retention_policy_name"."measurement_name"
```

I cannot reproduce this issue.  If using the above query format doesn't work, can you provide the actual queries, retention policy, and points used to produce the error?

**Comment by dneuman64** [comment]
Ah, did not know I need to query with the retention policy specified.  I will try that.
Thanks,
Dave
