### ISSUE TITLE
GROUP BY and SUM made results totally crazy in last RC 0.9rc29

### ISSUE THREAD

**Issue by dtouzeau** [influxdb/influxdb#2524]
For example, if you doing a query like this

SELECT SUM(test1) as test,test2 WHERE time>'2015-05-09 00:00:00' GROUP BY time(1h),test2
results are totally crazy and did not return expected results
Note that in 0.8, there are no issue on that

**Comment by toddboom** [comment]
@dtouzeau can you provide more information about the results and what you expected?

**Comment by dtouzeau** [comment]
I have a serie like this
![pic1](http://articatech.net/img/influx/09-05-2015 00-52-52.png)


For example, i have 2 sum in one query, the expected result is ok 
![pic3](http://articatech.net/img/influx/10-05-201508-49-05.png)

If you add a field in group by with no calculation, no data is displayed 

![pic2](http://articatech.net/img/influx/10-05-201508-50-34.png)

**Comment by beckettsean** [comment]
@dtouzeau in your example the MAC is a string that cannot be aggregated. Since you are using a GROUP BY in the query all results returned are aggregations. That's why the example with two SUMs works as expected: both are aggregations.

Even if you made the clause `GROUP BY MAC,time(10m)` you would not get buckets grouped by MAC and then by 10 minute intervals. In the current InfluxDB `time()` is always the primary GROUP BY parameter. I've made a note to make the docs more explicit on that point.

**Comment by dtouzeau** [comment]
Very disappointed on this limitation.
Worked on 0.8...
So to have expected results we must dump rows from Influx -> Insert rows into MySQL -> query MySQL with group by strings method ...

**Comment by beckettsean** [comment]
@dtouzeau If this is something you query frequently and the time ranges are uniform you could use continuous queries to replicate the functionality. You would likely need one per MAC address, though, so it could easily get out of hand.

The data structure changed significantly between 0.8 and 0.9, meaning some features are easier/faster and some are harder/slower/not possible. This is a feature that might return eventually but not in the short term.
