### ISSUE TITLE
Queries should return 4XX status codes when appropriate

### ISSUE THREAD

**Issue by aviau** [influxdb/influxdb#2560]
In the past, I would get a 500 when I tried to create a databse two times.

See [here](https://github.com/influxdb/influxdb-python/blob/ae45809e673e9779f579ba3a33a459110c643170/tests/influxdb/client_test_with_server.py#L334)

I updated from rc26 to rc30 and the issue appeared.

I would also get a 500 when dropping unexisting users, and other bad queries.

**Comment by neonstalwart** [comment]
looks like ea5a321 is what changed this.  @toddboom is it right that trying to create a database that already exists is no longer an error? see https://github.com/influxdb/influxdb/blob/e09cdede4a6801163b6c2a754bb6a95588232f72/httpd/handler_test.go#L218-L232

**Comment by toddboom** [comment]
@ReAzem this is actually intended behavior - changed in PR #2186. we decided that those specific queries should not be returning 500, since there's technically nothing wrong with the server (i.e. it's not an `Internal Server Error`). the queries are processed correctly, but the payload returned should have accompanying error messages.

**Comment by neonstalwart** [comment]
@toddboom does it seem inconsistent to have a success code but then the body has an error message?  should a client consider it a success or an error?

**Comment by neonstalwart** [comment]
i agree that 5XX statuses probably weren't correct.  what about some 4XX statuses though?  e.g. 404 for a database not found, 409 for trying to duplicate a database, etc.

**Comment by toddboom** [comment]
@neonstalwart we've probably had some variant of this discussion about a dozen times internally, so your points are definitely justified. i do agree with you, but the goal was to get it away from `5XX` codes to something a little more sane, and we can handle individual cases more specifically. some things like creating databases can be more idempotent-ish this way - there were a lot of cases where the `500` caused confusion or failing scripts.

**Comment by toddboom** [comment]
i like `409`, fwiw.

**Comment by neonstalwart** [comment]
yeah, i can see there's some back and forth and i like some of these being allowed to be idempotent - for example, i opened #2458 - but i think it may have swung too far the other way now.

**Comment by neonstalwart** [comment]
fwiw, since meaningful status codes can be just as useful as being idempotent for scripting (e.g. you can decide whether 409 is a really an error for your script or if it can be ignored) i could go either way on idempotent vs meaningful status codes but probably favor the status codes

**Comment by ReAzem** [comment]
I agree what ``5xx`` was bad, but I think that they should be ``4xx`` codes.

**Comment by josephglanville** [comment]
+1 for 4XX codes, they are semantic for bad queries etc as those are user/client errors.
200 OK is not semantically correct if things are not indeed "OK".

400 is nice for scripting as others have pointed out, most HTTP tools will return non-zero exit codes on non-2XX/3XX responses which is useful.

**Comment by toddboom** [comment]
ok, i'm going to rename this issue and try to clarify the status codes for each case. thanks for all the feedback!

**Comment by toddboom** [comment]
work began, discussion ensued. the group consensus is that for now, we're going to return a `400` for parser errors and continue to return a `200` for the time being, even for `NOT FOUND` or `ALREADY EXISTS` messages, partly due to the fact that queries can be grouped together and it may be difficult or impossible to determine a "proper" response code. additionally, most of the write path is going to change in the next week, which will obsolete some of these errors.

**Comment by beckettsean** [comment]
Believed fixed. Please open issues for specific return codes that seem problematic.
