### ISSUE TITLE
Question: Information about 0.9 shards and retention policies

### ISSUE THREAD

**Issue by arunoda** [influxdb/influxdb#2570]
Hi,

I wanna to know more about Shards and Retention policies in 0.9. 
Current 0.9 documentation is pretty basic and I want to read more on that.

Is is the same as 0.8 or is their any major changes?
If so, I'd like to have some pointers to explore more on that.

Thanks.

**Comment by beckettsean** [comment]
The major change in 0.9 is that shards are no longer under direct user control. The shard groups are generated automatically by the database based on the retention policy duration and replication factor.

**Comment by arunoda** [comment]
Okay. That makes sense.

So, everytime I mention a new retention policy, it'll try to create a
shard. Or is there anymore logic happening here? If so, I'd like to know
that. May be you can refer me the place where this happens in code.

**Comment by beckettsean** [comment]
Shards belong to shard groups which belong to retention policies. Therefore for each retention policy you create there is at least one additional shard group created, and likely more. Each shard group has at least one distinct shard. There is no attempt to de-duplicate shard creation, as the number of retention policies on a database is assumed to be a small number, perhaps a few dozen in the extreme.

Can you open a documentation issue on the influxdb/influxdb.org repo instead of the core database repo? Thanks!

**Comment by arunoda** [comment]
Yes. sure. I can open an issue.
I didn't knew there was a project on there.

Thanks for your time.
