### ISSUE TITLE
Regex not working for columns with single digits?

### ISSUE THREAD

**Issue by ericjmiller** [influxdb/influxdb#2573]
I have a query that needs to return all data where 'thread_id' is in some range (say, [0-9] as an example).  I most likely need to use regex because I need this query to work as the 'all glob' in Grafana (but nevermind that if you don't know what I'm talking about).  

My query: select * from table_name where thread_id =~ /[0-9]/

and it simply returns nothing.  I need it to be in this format for reasons having to do with Grafana.  Am I doing something wrong here?

**Comment by toddboom** [comment]
@ericjmiller is thread_id being written in as a string?

**Comment by ericjmiller** [comment]
My script write it into the json as a float - so it's not a string.  How does that affect the results?

**Comment by otoolep** [comment]
`thread_id` is a field, not a tag, right?

**Comment by beckettsean** [comment]
If `thread_id` is a tag then regardless of how it's being written to the database it is being stored as a string. Not sure why that would affect the regex, however.

If `thread_id` is a field, then it is not indexed. In order to do the regex matching the query must traverse all points in the `table_name` measurement. Since there is no WHERE clause and thus no time restriction, it would have to load all points ever recorded on the `table_name` measurement, which could take minutes and might appear to be non-responsive, especially if grafana has timeouts waiting for the data.

**Comment by ericjmiller** [comment]
I didn't submit thread_id as a tag.  If I do, will it respond to regexes?

**Comment by beckettsean** [comment]
Field values don't appear to be searchable by regex, at least not in my tests. This seems like a reasonable limitation given that fields aren't indexed. Tags are certainly searchable by regex and I just verified that on RC30.

Given that this is a value that you want to use in your queries, it should be a tag, anyway. Tags are indexed, fields are not. Querying by fields is thus much less performant. Fields are meant for the actual metric, whatever you might want to SUM or graph. Tags are for metadata, like the `thread_id` from which the measurement came.
