### ISSUE TITLE
0.9rc30: Query planner should return syntax error if regex is applied to fields

### ISSUE THREAD

**Issue by dtouzeau** [influxdb/influxdb#2593]
The query 
SELECT *  FROM access_log WHERE SITE ='198.38.120.151'
Works as expected ( 1200 rows)
The Query 
SELECT *  FROM access_log WHERE time >'2015-05-19 12:00:00' AND SITE ='198.38.120.151'
Works as expected  ( 300 rows)

But queries
SELECT *  FROM access_log WHERE SITE =~ /198.38.120..*/
SELECT *  FROM access_log WHERE time >'2015-05-19 12:00:00'  AND SITE =~ /198.38.120..*/
SELECT *  FROM access_log WHERE time >'2015-05-19 12:00:00'  AND SITE =~ /.*something.*/

return no row

**Comment by beckettsean** [comment]
@dtouzeau is `site` a tag or a field in the `access_log` measurement?

**Comment by dtouzeau** [comment]
It is a field not a tag

**Comment by beckettsean** [comment]
I believe this is expected behavior, then. Fields and field values cannot be searched with regular expressions. 

Do you get any error messages or just a blank response?

**Comment by dtouzeau** [comment]
Just blank response, no row
Is there a way to define all fields as tags because all fields that have created is able to be searched.
This way that makes difference between fields and tags force to define many field as tags and should growth database size...
Example for a mail server we have time, mail from, mail to, domain from domain to, size, hits...
So i must set as tag  mail from, mail to, domain from domain to and field too...

**Comment by dtouzeau** [comment]
Is the "GROUP BY" feature should work better with tags ?

**Comment by beckettsean** [comment]
Everything in a query will work better on tags rather than values. Tags are indexed, fields are not. Fields should only contain actual measurements. Tags should contain metadata about the measurements. 

Putting it another way, anything you want to frequently use as part of the WHERE clause in your queries should be a tag. In your examples, `time`, `size`, and `hits` sound like fields and `mail from`, `mail to`, `domain from`, and  `domain to` could be tags or fields. It really all depends on the queries you most want to run. 

InfluxDB is intended for use cases where queries are primarily about the change in the measured values over time. The query examples you give in your initial question look like traditional RDBMS queries with a `time` component in the WHERE clause.

**Comment by dtouzeau** [comment]
Yes my needs is like MySQL but i need InfluxDB performance, we build an Appliance for Squid server and we have to provides statistics on millions Web requests.
MySQL is too heavy and require too many performances (memory/CPU) for storing million items in one single table/database...

The 0.8 version was very good because the mechanism was the same as MySQL but the last bug about listen port 8086 force us to upgrade to 0.9 as the method was radically different.

I think you are in the right way about performances between MySQL it is amazing...!  

Now we have a 0.9x DB that stores about 500MB data without any tag.. 

Is there a way to create tags in a bulk way ?
If not, this is my feature request...

**Comment by beckettsean** [comment]
@dtouzeau the performance of InfluxDB relative to MySQL is precisely because InfluxDB restricts what queries can be done and optimizes for those cases. There are queries that are performant in MySQL that are impossible in InfluxDB and vice versa. 

As I mentioned, without some idea of what queries you want to run on a regular basis it's not possible to determine whether you should be using a time-series database to store them.

>Is there a way to create tags in a bulk way ?

There is no way to add tags to a point. Points are uniquely identified by their timestamp, measurement, and tag set. Adding a new tag changes the tag set and therefore makes it a new point.

**Comment by lokeshverizon** [comment]
does that mean, we can NOT use regex in the field at all. Tag is the only way to do faster search.

**Comment by beckettsean** [comment]
@lokeshverizon Regular expression matching only works against tags, not fields.
