### ISSUE TITLE
Should I use tag for userId when having a million users?

### ISSUE THREAD

**Issue by abeninskibede** [influxdb/influxdb#2626]
Hey guys I read that tag cardinality should be less than 100k but I have a series and I have a series with user data I want to be able to draw a graph for a given user. Is it a good idea to use a tag by userId when having more than 1 million users and user data 30-40 million rows? And if not what should I do?

**Comment by marcosnils** [comment]
@abeninskibede I believe the best way would be to add the user_id as a column in the user data series and then use continuous queries to pre-populate the graphs you want to do. As the user_id won't be indexed in the user data series querying against that series won't be practical. But if you make use of continuous queries you can have your data pre-populated to show different kind of graphs

Hope it helps!.

**Comment by marcosnils** [comment]
BTW: Going for the tag alternative is not an option as I've tried that before and it will definitely won't scale.

**Comment by abeninskibede** [comment]
Hey there,
thank you for your answer but I can't seem to understand how would continuous queries solve my problem?
EG: 

I have the following schema {userId: string, value: long}
I have data for 10 days.
I want do draw a graph showing the data for the past 2 days for user with id = 5.

When I say: `select * from userData where time > '2015-05-19' where userId = 5`
Even when using continuous queries influx will first select a set of data from the 19th to 21st for all users and then make a full table scan to filter out the results for user with id = 5.

I would be very grateful if you give me an example.

**Comment by marcosnils** [comment]
@abeninskibede that's exactly how it works. The first time the CQ will run it will take a lot of time because it need to make a full scan into the raw series. 

But if you make a downsample of that data (IE. weekly / daily / hourly) then the CQ will only update the new records and will not need to re-process the whole raw data again. CQ's will only backfill data when they're created and then just apply new data periodically. 

That way you can have downsampled series like this:

`select count/sum/avg(value), user_id from userData where time > '2015-05-19' group by time(1d), user_id` >> not sure about the query syntax

Then querying daily / monthy / hourly data should be quite fast if you go to the corresponding series .

**Comment by marcosnils** [comment]
In conclusion: You'll always end up doing full scans to look for the specific user_id but if you downsample correctly you shouldn't have to go through a really huge data set to get the info you're looking for.

Keep in mind that influx cares about time series... you do have the tags option but it's very limited to get indexed data out of it.

**Comment by abeninskibede** [comment]
Thanks for the answers mate!

**Comment by neonstalwart** [comment]
@marcosnils i was under the impression that using a tag is going to result in effectively the same thing as running a CQ to populate another measurement  can you explain why a CQ is better than using a tag?

**Comment by neonstalwart** [comment]
> effectively the same thing as running a CQ to populate another measurement

this is assuming that the CQ writes to a separate series per user and the tag includes the userid.

however, using a CQ to downsample (as you've suggested) and then scan by user over a subset of time would be effective in cases where you want to query over random time ranges but if you had a case where you might let each user see their own data then tags would seem to be the right choice since i would think that would be more efficient at seeing all the data for one user.

**Comment by marcosnils** [comment]
@neonstalwart the tag approach is not viable as it will require huge amount of memory to keep millions of users indexed and to keep cardinality of all those values. I've tried to do that in the past with a 2M unique tag values and in a 64GB single instance influx was running out of memory. 

> this is assuming that the CQ writes to a separate series per user and the tag includes the userid.
I wasn't thinking about generating one series per user, my idea was to generate downsampled series which will help to query the information "per time" based for the user.

**Comment by marcosnils** [comment]
@neonstalwart I believe it's a trade-off between filtering the data on dynamo and doing it in your application if you can handle it . However, I will insist in not using tags as having a high cardinality really causes resource degradation and bad performance.

**Comment by tcompart** [comment]
Therefore if I have 7 million users and they will look at monthly, daily and hourly values, I should have 7 million * 3 series, right?

Or should I have 7 million users in 3 different series regarding the aggregation (monthly, daily etc.), and still filter by the userid tag? E.g. CQ plus Tags.

Would there also be a way to limit the number of users, which are indexed and kept in memory?

**Comment by beckettsean** [comment]
This is a great discussion, but it is more appropriate for the influxdb@googlegroups.com mailing list, as there are no actions to be taken with respect to the code.

Alternately raise this as an issue on the documentation, which is sorely lacking in details on how to design a schema.
