### ISSUE TITLE
Duplicated entries when using `fill(0)`

### ISSUE THREAD

**Issue by inkel** [influxdb/influxdb#2662]
Hi everyone:

I'm using Influxdb in conjunction with Grafana, and there were some funny graphs, so I've investigated what could be the issue. I've found that sending the following query to my Influxdb installation returns _duplicated_ entries with a different value, for instance:

```
select mean(value) from "local.jvm.mem.heap_committed_in_bytes"
where time > 1432670387s and time < 1432670403s
group by time(10s) fill(0) order asc
```

returns:

```
[{"time"=>1432670380, "mean"=>16801857536.0},
 {"time"=>1432670390, "mean"=>16801857536.0},
 {"time"=>1432670400, "mean"=>0},
 {"time"=>1432670380, "mean"=>0},
 {"time"=>1432670390, "mean"=>0},
 {"time"=>1432670400, "mean"=>0}]}
```

But when I remove the `fill(0)` the result is:

```
[{"time"=>1432670380, "mean"=>16801857536.0},
 {"time"=>1432670390, "mean"=>16801857536.0}]
```

Do you guys have any clue on why this might be happening? Thanks.

**Comment by beckettsean** [comment]
Are you using version 0.8 or 0.9? 

In 0.8 it is possible to have two points with the same timestamp. They are differentiated by sequence numbers. If one point has a value and the other doesn't that would explain why you see two values for the same timestamp when using `fill(0)`.

**Comment by inkel** [comment]
We're using version 0.8.8. Is there a way to fix that or just by upgrading to 0.9 will solve it?

**Comment by beckettsean** [comment]
The feature is behaving as intended, in that it's filling in zeroes for points that don't have an explicit value. To avoid the problem in the future you could specify unique timestamps for all points, which would prevent duplicate points.

Can you provide the output of `select * from "local.jvm.mem.heap_committed_in_bytes"
where time > 1432670387s and time < 1432670403s`, just so we can verify that the issue is due to multiple points at the same timestamp?

For 0.9 it is not possible to have two points with the same values, so this issue cannot happen. Writing in a new point with identical timestamp, tag set, and measurement name silently overwrites the older point.

**Comment by inkel** [comment]
Thanks for the explanation, @beckettsean. This is the output of the query you asked:

```
[{"time"=>1432670398, "sequence_number"=>9966816670001, "value"=>16801857536.0},
 {"time"=>1432670396, "sequence_number"=>9966760930001, "value"=>16801857536.0},
 {"time"=>1432670395, "sequence_number"=>9966718200001, "value"=>16801857536.0},
 {"time"=>1432670388, "sequence_number"=>9966660990001, "value"=>16801857536.0}]
```

It doesn't seem to be the case of multiple points in the same timestamp if I understand correctly, right?

**Comment by beckettsean** [comment]
@inkel Thanks for the query output. I agree it looks like a bug in the 0.8.8 `fill(0)` feature rather than a duplicate points issue. I'm not sure there's a workaround. There are no planned fixes for 0.8 bugs, so it might be better to move to 0.9 when ready.

I've verified that 0.9 does not have this issue:

```
> select * from fill0 where time > 1432670387s
name: fill0
-----------
time			value
2015-05-26T19:59:48Z	1.6801857536e+10
2015-05-26T19:59:55Z	1.6801857536e+10
2015-05-26T19:59:56Z	1.6801857536e+10
2015-05-26T19:59:58Z	1.6801857536e+10

> select mean(value) from fill0 where time > 1432670387s and time < 1432670403s group by time(10s) fill(0) 
name: fill0
-----------
time			mean
2015-05-26T19:59:40Z	1.6801857536e+10
2015-05-26T19:59:50Z	1.6801857536e+10
2015-05-26T20:00:00Z	0
```

The 0.8 datastore is incompatible with 0.9 and we have not yet written any data migration helper tools. If you can start over on 0.9 then now's a reasonable time to do so. Otherwise I'd advise waiting a month or so until there's more migration help.

**Comment by inkel** [comment]
That's a pitty. Hopefully you guys come up with a migration tool sooner than that :smile_cat: 

Thank you for your time, @beckettsean.

**Comment by epelc** [comment]
@inkel Did you graphs look like this by any chance? I think I'm having the same issue
Notice the overlap at wed 10. I also have graphs with multiple overlaps in them.
![badgraph](https://cloud.githubusercontent.com/assets/5204642/8150562/4b25ac50-12bc-11e5-8945-aeeb375c61ba.PNG)

It also seems to be happening anytime I use `fill(x)` no matter what I use for `x`. My example query
`SELECT count(totalWeight) FROM someSeries WHERE time > now() - 7d GROUP BY time(1d) fill(0)`

**Comment by inkel** [comment]
@epelc yes, it looks something like that :disappointed:
