### ISSUE TITLE
[v0.9.0-rc31] Error describing databases

### ISSUE THREAD

**Issue by MdSE** [influxdb/influxdb#2677]
After update to v0.9.0-rc31 the program stop working.
When I Run:

influxDB = InfluxDBFactory.connect("http://" + influxHost + ":"
				+ influxPort, influxUser, influxPassword);
influxDB.describeDatabases();

I get this exception:
RuntimeException: 404 page not found 

Im using JAVA API 1.5

Does anyone know how to solve this issue?

**Comment by beckettsean** [comment]
@MdSE What version were you running before upgrading to RC31? 

This sounds more like an issue with the Java client than with the database. Can you verify that the following works:

`curl -G 'http://<hostname>:8086/query' --data-urlencode 'q=CREATE DATBASE <db_name>'`

If that works then the issue is not with InfluxDB but with the Java client. You can open an issue for that repo here: https://github.com/influxdb/influxdb-java/issues/new

**Comment by mnuessler** [comment]
Does the Java client actually already support the new API of InfluxDB 0.9? There is open issue regarding compatibilty (influxdb/influxdb-java/issues/22).

**Comment by MdSE** [comment]
@beckettsean I was using 0.8.8. 

When I run:
 curl -G 'http://localhost:8086/query' --data-urlencode 'q=CREATE DATABASE multittest'
It returns:
{"results":[{}]}
and the database is created.

Thanks for your help

**Comment by beckettsean** [comment]
@MdSE thanks for the extra detail. The changes between 0.8 and 0.9 are substantial. Most of the query language has been updated, so very few things that work on 0.8 will work unaltered on 0.9, and most clients are waiting until 0.9 final to update their version support.

I'm glad the straight curl commands are working and stay tuned to the influxdb/influxdb-java repo for updates on that client.
