### ISSUE TITLE
UDP/IP message format

### ISSUE THREAD

**Issue by wdalmut** [influxdb/influxdb#2850]
Hi,

i see that in RC 31 the UDP/IP format is a JSON message equals to the HTTP implementation.

In RC 32 i see that now the UDP/IP message is a simple string separated by commas, like:

```
cpu,region=us-west,host=serverA,env=prod,target=servers,zone=1c,tag1=value1,tag2=value2,tag3=value3,tag4=value4,tag5=value5 value=1 1000000000
```

Can i ask why this change? The JSON format with the database name, serie name, tags and fields is not a more valid option than that string?

**Comment by neonstalwart** [comment]
@wdalmut lots of info at #2696.  bottom line (no pun intended), the line protocol is significantly more performant than JSON.

**Comment by toddboom** [comment]
@wdalmut As @neonstalwart mentioned, the switch was made for performance reasons. The JSON parsing was staggeringly inefficient, even in the best scenarios, and rapidly becomes a bottleneck. Since the UDP input is primarily used for higher-throughput situations, it became clear that supporting the line protocol was the only logical move for us.

Since there's not an actionable issue here, i'm going to close this out, but definitely let us know if we can answer any other questions about the decision.

**Comment by wdalmut** [comment]
Thanks for the related issue and the explanation, i don't like it but that is my problem... :smile:
