### ISSUE TITLE
Field mismatch error messages need to be updated

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#2908]
After #2885 the write error messages for field type mismatch aren't friend. Like this `write failed: field type conflict: input field "value" is type int64, already exists as type %!s(influxql.DataType=1)`

Update to convert that data type to a string for more friendly error messages.

**Comment by davidbirdsong** [comment]
Could I ask that this error also include the measurement? I'm converting json to line protocol and writing via UDP and having a lot of trouble tracking down problems w/ my converter.

**Comment by Jhors2** [comment]
Hey @pauldix 
Can you also describe when this happens?  it is creating a massive cluster inconsistency that I do not understand (There is only one pusher script always writing value as type int).

**Comment by jwilder** [comment]
@Jhors2 It happens when you write a point field as one type initially and write a different type later.  For example, if you write `cpu value=0`, the type will be an integer.  If you later write `cpu value=0.5`, the type written is a float but the field type is an integer so you get this error.  If the initial write was `cpu value=0.0`, the field type would be defined as a float and the second write would succeed.

If you are using the line protocol and writing float data, it needs to always have a decimal in the value.  If it's integers, no decimals.

**Comment by Jhors2** [comment]
Awesome, thanks!
