### ISSUE TITLE
[0.9.0] line protocol: inserting multiple points without timestamp loses points

### ISSUE THREAD

**Issue by neonstalwart** [influxdb/influxdb#2934]
if i try to insert multiple points without a timestamp, only the last one is used.  i assume this is because they are all sharing the same timestamp.

should they each get a different timestamp or is this an invalid use case?  fyi: i don't have a need to be able to do this - it was done just as part of trying to make a script that might reproduce #2883

```sh
echo "creating database"
curl -G -ipv4 http://localhost:8086/query --data-urlencode "q=CREATE DATABASE foo"

echo "inserting data"
curl -d \
"score value=1
score value=2
score value=3" -ipv4 http://localhost:8086/write?db=foo

sleep 5

curl -G -ipv4 http://localhost:8086/query --data-urlencode "q=select value from score" --data-urlencode "pretty=true" --data-urlencode "db=foo"

```

EDIT: i'd lean towards it being invalid input - i can't seem to think of a situation where this would make sense.

**Comment by beckettsean** [comment]
It is an interesting question. In order to trigger this the user must provide multiple points with identical tag sets and no timestamps. I don't think we can know whether they intend the values to overwrite previous or add new points a few nanoseconds apart. I lean towards documenting the behavior for now and mark this RFC to see what the community prefers. 

RFC question: When writing multiple points in a batch that have matching tag sets but no timestamps, should all the points be added with slightly different timestamps, or should one point win and all others be dropped? If the latter, which should win, the first point or last point parsed?

**Comment by neonstalwart** [comment]
alternatively, should it be an error to try to send more than 1 point with matching tags but no timestamps?

**Comment by jwilder** [comment]
Currently, any points without timestamps in a batch all receive the same timestamp.  That last one wins because it's the last point that is actually written when iterating over the points.  We could assign a new timestamp to each point as well but its always better to send points in with timestamps.

I don't think we should reject the write as it would cause extra overhead during parsing to detect this edge case which will slow things down for all writes.

**Comment by beckettsean** [comment]
this is a wontfix for now.
