### ISSUE TITLE
Feature Request:support tags delete 

### ISSUE THREAD

**Issue by huhongbo** [influxdb/influxdb#3007]
Now the influxdb can create tags but there is no way to delete or modify the tags
use case
I use hostname as tag ,so if the hostname is offline then I want to delete it 
or I add the wrong tag, I want to modify or delete it

**Comment by beckettsean** [comment]
Tags are part of the index for the series, so this is actually asking to do a partial delete on the index. I don't think there's any clean way to do that. For instance, if two points have the same timestamp but differ by one tag value, what happens when that tag value is deleted? Are the points merged? Is one silently dropped? If so, which one?

@huhongbo Does DROP SERIES meet your needs? See the "Dropping measurements and series" section on https://influxdb.com/docs/v0.9/query_language/querying_data.html for details of that query.

**Comment by huhongbo** [comment]
how about drop all point associate with tags and remove tags also

**Comment by beckettsean** [comment]
@huhongbo tags and series are not independent things. A series is defined by its tag set. If the tag exists, it defines a series. 

If you drop a series that deletes the series from the index. Since the tags are part of the index and that is the only place they are stored, that also drops the tags. Dropping a series also deletes all points in that series.

Perhaps it would help the discussion if you can provide some example data and describe what you want to see happen when deleting a tag.
