### ISSUE TITLE
[0.9.0] Ubuntu 14.04 web UI cannot insert points

### ISSUE THREAD

**Issue by maxcanada** [influxdb/influxdb#3015]
Hi, 

Writing a simple value via the web UI doesn't seem to work (Firefox and Chrome) : 

Time Series Name : trades 
Values : 
{
"value" : "test"
}

In my console, I can see that a "POST" request is sent to : "http://localhost:8086/db/prncpssdb/series?u=root&p=root", which returns a 404 not found.

**Comment by neonstalwart** [comment]
that url is completely wrong for 0.9.0.  are you sure you're using the web ui for 0.9.0?

**Comment by maxcanada** [comment]
Actually no. I upgraded from 0.8 to 0.9.0. The engine is definitely 0.9.0, but how can I make sure that I am using the web ui for 0.9.0 ?

**Comment by neonstalwart** [comment]
@maxcanada it's possible that your browser has cached the previous UI if you happen to have been using it on the same port previously.  you can clear your browser's cached and/or try running the admin UI on a different port so that the browser isn't using cached code.  ultimately, you should only see requests to /query or /write with the latest admin UI.

**Comment by maxcanada** [comment]
Oh thanks, I guess that was it. I cleared the cache several times before with no luck.
I tried in private window mode and it was working.
Then I hard reset the cache.
Now it's working
Thansk
