### ISSUE TITLE
continous queries problem

### ISSUE THREAD

**Issue by hy05190134** [influxdb/influxdb#3046]
I want ensure that whether continuous queries include "group by" should include "where time ..."? (but it doesn't describe in the docs )and another question is whether every shell command like "select * from xxx" have a equal request using curl like "curl ...."?

**Comment by hy05190134** [comment]
how to show retention policy?

**Comment by hy05190134** [comment]
can you add more configuration details for fresh to deploy?

**Comment by beckettsean** [comment]
@hy05190134 a number of your recent issues are not feature requests or bug reports, but more support questions. Please send them to support@influxdb.com rather than opening a GitHub Issue. Thanks!

`WHERE time` should not be part of a CQ. There's a bug #2944 that incorrectly requires them. That should be fixed for 0.9.1.

The documentation for retention policies is here: https://influxdb.com/docs/v0.9/query_language/database_administration.html. The command you want is `SHOW RETENTION POLICIES <database_name>`.

I don't understand your final comment, but it sounds like a support question. Please contact the mailing list (influxdb@googlegroups.com) or support@influxdb.com for assistance.
