### ISSUE TITLE
unquoted string for field value is always interpreted as boolean "false", unless the unquoted string is "true"

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#3063]
```
> insert boolean value=filibuster
> insert boolean value1="filibuster"
> insert boolean value2=aslkdjaklsjd
> insert boolean value3=tryrye
> insert boolean value4=true
> select * from boolean
name: boolean
-------------
time				value	value1		value2	value3	value4
2015-06-18T18:49:37.143564634Z	false					
2015-06-18T18:49:56.736602833Z		filibuster			
2015-06-18T18:54:37.436111629Z				false		
2015-06-18T18:54:44.179786202Z					false	
2015-06-18T18:56:49.072791322Z						true
```

Shouldn't an unquoted string that isn't `true` or `false` throw some form of parser error instead? This is a very easy mistake to make and since field types cannot be changed, it means the field is forever a boolean.

**Comment by mukatee** [comment]
This is also an issue with the Java driver: https://github.com/influxdb/influxdb-java/issues/39

Is there some documentation somewhere that shows how different types should be encoded? Also, the server prints a boolean parse error for these in its own logs, so perhaps it could also return an error value if it is not "true" or "false"?

I also had some other similar issues with the encodings such as if my string has spaces in it, the database gives a "bad timestamp" error. My guess is because it uses spaces to identify the timestamp but does not look for the last space but rather first space that comes after field definitions.

So, I am looking for some documentation on how things should be encoded and maybe hoping for some more informative errors :)

**Comment by jwilder** [comment]
Fixed by c97ded.  A parsing error will be returned by the API.

@mukatee See https://github.com/influxdb/influxdb/blob/master/tsdb/README.md
