### ISSUE TITLE
[0.9] When inserting huge number of single point records using curl script, some get rejected

### ISSUE THREAD

**Issue by shilpisharma** [influxdb/influxdb#3292]
I was trying to insert around 70000 records using curl. Something like this:

```
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF2 value=36.13 1359723600000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF2 value=35.26 1359724500000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF2 value=36.02 1359725400000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF2 value=36.35 1359726300000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF2 value=36.65 1359727200000'
```

Around 2500 got rejected due to following reasons:

1. write failed: field type conflict: input field "value" is type int64, already exists as type %!s(influxql.DataType=1)
2. write failed: database not open - 680 such errors.

It seems like influxdb closes many a times in between. Any solution to avoid this? 

Also I know it's possible to pass multiple datapoints in single command, but I believe the upper limit is 500. Can you suggest and alternative to this.

Rest of the records got rejected because datatype expected was float and value being passed was integer. Is there any plan where automatic upcasting of datatype from int to float will be done in future?

**Comment by samhatchett** [comment]
I saw this kind of error when I didn't make absolutely sure that the "value" had a decimal point. Otherwise the db interprets as int64, which conflicts with the column type that's already associated with that key.

**Comment by beckettsean** [comment]
> It seems like influxdb closes many a times in between. Any solution to
avoid this?

Making 70k consecutive single-point inserts will definitely cause
performance issues, sounds like the db is crashing or falling behind very
badly and causing timeouts. You should be batching those inserts into files
so that one curl command can pass 1,000-5,000 points. The upper limit is
not defined, but past about 5,000 points in a batch performance generally
gets worse.

> Also I know it's possible to pass multiple datapoints in single command,
but I believe the upper limit is 500. Can you suggest and alternative to
this.

Not sure where you got the idea that 500 is the limit. If that's in the
docs please let us know. 5k is the generally accepted place to begin with
batches.

> Rest of the records got rejected because datatype expected was float and
value being passed was integer. Is there any plan where automatic upcasting
of datatype from int to float will be done in future?

Not at this time. Type-casting is expensive, and writes need to be as
performant as possible. The less the db has to worry about regularizing the
incoming data the faster it can write to disk. As long as the values passed
have a decimal point they will parse as floats (e.g. 123 is an integer,
123.0 is a float).

On Fri, Jul 10, 2015 at 11:14 AM, shilpisharma <notifications@github.com>
wrote:

> I was trying to insert around 70000 records using curl. Something like
> this:
>
> curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms'
> -d 'tempF2 value=36.13 1359723600000'
> curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms'
> -d 'tempF2 value=35.26 1359724500000'
> curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms'
> -d 'tempF2 value=36.02 1359725400000'
> curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms'
> -d 'tempF2 value=36.35 1359726300000'
> curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms'
> -d 'tempF2 value=36.65 1359727200000'
>
> Around 2500 got rejected due to following reasons:
>
>    1. write failed: field type conflict: input field "value" is type
>    int64, already exists as type %!s(influxql.DataType=1)
>    2. write failed: database not open - 680 such errors.
>
> It seems like influxdb closes many a times in between. Any solution to
> avoid this?
>
> Also I know it's possible to pass multiple datapoints in single command,
> but I believe the upper limit is 500. Can you suggest and alternative to
> this.
>
> Rest of the records got rejected because datatype expected was float and
> value being passed was integer. Is there any plan where automatic upcasting
> of datatype from int to float will be done in future?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdb/influxdb/issues/3292>.
>



-- 
Sean Beckett
Director of Support and Professional Services
InfluxDB

**Comment by beckettsean** [comment]
@shilpisharma what version of InfluxDB are you running?

**Comment by shilpisharma** [comment]
I am using the latest stable release 0.9.1. I recently updated.

By 500 datapoints insertion at once, I meant using single curl command I was able to insert around 500 records. There is no document, it was more trial and error. I was able to insert 500 datapoints at once. When I tried 600, it gave too many arguments error. 

Not sure where you got the idea that 500 is the limit. If that's in the docs please let us know. 5k is the generally accepted place to begin with batches.

**Comment by beckettsean** [comment]
@shilpisharma If you want to pass many points via `curl` you should pass a file to curl, not a long list of arguments. For example:

`curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' --data-binary @<file>` where `<file>` is the path to the file containing up to 5,000 points in the line protocol format, separated by newlines (`\n`). If the lines are separated by anything other than a bar newline (e.g. carriage return + line feed) you will get a syntax error like `': invalid number...`
