### ISSUE TITLE
measurements should be scoped to retention policies

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#3341]
related to #3318 

Non-existent measurement gives a meaningful error:

```
> select * from foobar
ERR: measurement not found: "telegraf"."default".foobar
```

Measurement in the wrong retention policy gives no error or meaningful output:

```
> select * from sys_load1
name: sys_load1
---------------
time	max_load

> select * from month.sys_load1
name: sys_load1
---------------
time			max_load
2015-07-13T21:00:00Z	2.43
2015-07-13T22:00:00Z	2.27
2015-07-13T23:00:00Z	2.23
2015-07-14T00:00:00Z	1.77
```

**Comment by beckettsean** [comment]
Discussions with @pauldix lead us to believe that measurements "exist" in all retention policies for a given database, which seems non-intuitive and contradicts our docs, which state that measurements are scoped exclusively within a retention policy. If I haven't created a measurement in a given RP, it seems like it shouldn't be there.

**Comment by pauldix** [comment]
The new behavior on the query engine is that if you select from a measurement that doesn't exist, you'll get an empty result. This is because there is no central authority for which measurements exist where.

They're now stored on a per shard basis. So if you happen to construct a query against a measurement that hasn't written any data into any of the shards that have to be hit for the query, you'll get an empty result.

Closing this out since it's no longer valid.

**Comment by beckettsean** [comment]
@pauldix makes sense. It's going to be a bit confusing that empty result means "wrong retention policy" or "doesn't exist" or "doesn't have data on any active nodes" but the alternative is much much worse.
