### ISSUE TITLE
dissallow more than one CQ on the same target table

### ISSUE THREAD

**Issue by gucki** [influxdb/influxdb#3382]
Having more than one CQ on the same target table ("netskin"."1m"."net" here), doesn't work. The latest CQ seems to silenlty override/ discard the data of any other CQs on the same target table.
 
    CREATE CONTINUOUS QUERY "max" ON "netskin" BEGIN SELECT MAX(value) AS max INTO "netskin"."1m"."net" FROM "netskin"."default"."net" GROUP BY time(1m),* END

The target table only contains results of "max". OK.

    CREATE CONTINUOUS QUERY "min" ON "netskin" BEGIN SELECT MIN(value) AS min INTO "netskin"."1m"."net" FROM "netskin"."default"."net" GROUP BY time(1m),* END

The target table only contains results of "min", not "max" anymore. BUG. Deleting the "min" CQ makes the "max" CQ work again as expected.

    CREATE CONTINUOUS QUERY "min.max" ON "netskin" BEGIN SELECT MAX(value) AS max, MIN(value) AS min INTO "netskin"."1m"."net" FROM "netskin"."default"."net" GROUP BY time(1m),* END

This works as expected.

Possible solution: disallow creation of more than one CQ for the same target table.

**Comment by beckettsean** [comment]
@gucki this is expected behavior, as only one point can exist per measurement+tagset+timestamp.

Both of your continuous queries are writing into the `net` measurement in the `default` retention policy of the `netskin` database. You're grouping by the same time interval, so the timestamps will be identical, and you're grouping by `*` so the tag sets are duplicated. You're writing two different fields, `max` vs `min`, but fields aren't part of a point's uniqueness, only the measurement, tag set, and timestamp define a unique point.

So both CQs are running just fine, but the `min` CQ apparently runs ever so slightly after the `max` CQ and thus silently overwrites every `max` field with the `min` field.

Your workaround is the right way to do it, write each point with both values, thus preventing them from squashing each other.

It's possible that we could have the CQ parser throw an error if someone tried to make duplicate CQs writing to the same measurement with the same GROUP BY interval and also a GROUP BY *, but that's more of a documentation thing to fix, I would think.

**Comment by gucki** [comment]
@beckettsean Thank you for your detailed reply. Another option would be to have a `INSERT ... ON DUPLICATE UPDATE ...` behavior. That way the second CQ would simply set/ update the `min` value, not changing the existing `max` value form the first CQ.

**Comment by beckettsean** [comment]
@gucki InfluxDB achieves higher write and read throughput by ignoring some of the classic RDBMS features that rarely apply to time series data, UPDATE being a prime example. Unless there's a fundamental driving need for it, UPDATE will continue to be unsupported.

**Comment by gucki** [comment]
@beckettsean Makes sense :+1:

**Comment by beckettsean** [comment]
Opened https://github.com/influxdb/influxdb.com/issues/140 to address this in the docs.
