### ISSUE TITLE
cannot query by tag  v0.9.2

### ISSUE THREAD

**Issue by airyland** [influxdb/influxdb#3534]
When I queried by `select * from recommend`, I got everything.

![image](https://cloud.githubusercontent.com/assets/559179/9030933/8221a71c-39dc-11e5-96f6-0e323259888f.png)

But when I queried by tag `select * from recommend where version='4.2.0'`, I got nothing.

**Comment by beckettsean** [comment]
Certainly I have no issue querying by tag in 0.9.2, so there's something specific to the data or syntax here.

Can you copy/paste from `curl` commands or the CLI rather than the admin UI? It's much easier for us to debug with actual ASCII output rather than screenshots.

Please give a sample write statement so we can see the structure of your points, and please provide the CLI or `curl` output for `select * from recommend` and `show series`

**Comment by mjdesa** [comment]
I think that the `"`'s are being included in your tag value. Try running

```
select * from recommend where version='"4.2.0"'
```

**Comment by airyland** [comment]
@beckettsean @mjdesa  Thank you. You are right, I make a mistake when sending data to the server use the following syntax:

`recommend,type=2,plat="android",version="4.3.1" url="38178993",ip="123.*.*.*",token="dfsfsfo2549848e7" 1438178654000000000`

**Comment by airyland** [comment]
But when I remove the ", I got the error.

`recommend,type=1,plat=ios,version=4.3.1 url=undefined,ip=42.*.*.*,token=55ee****1438647733000000000`

`Failed to write: unable to parse 'recommend,type=1,plat=ios,version=4.3.1 url=undefined,ip=42.227.198.53,token=55ee1da002sdfdsf 1438647733000000000': invalid boolean`

**Comment by airyland** [comment]
I see. field value must use " while tag value not..

**Comment by mjdesa** [comment]
@airyland yup, all tag keys and values are treated as strings so no quotes are needed. However field values can be integers, floats, strings, or booleans. Hence if you're writing a string, as a field value you must include the quotes.
