### ISSUE TITLE
Select field values while using aggregate functions

### ISSUE THREAD

**Issue by pranavrajs** [influxdb/influxdb#3536]
How can we select a field value while using aggregation functions? 
```
SELECT COUNT(DISTINCT empid), empid FROM series WHERE time > now() - 10h GROUP BY empidtag,time(1h)
```
This query returns count and timestamp with empid null

**Comment by beckettsean** [comment]
I don't quite understand what the query is trying to do. 

`SELECT COUNT(DISTINCT empid) FROM series WHERE time > now() - 10h GROUP BY empidtag,time(1h)` makes sense as a query, and `SELECT empid FROM series WHERE time > now() - 10h GROUP BY empidtag,time(1h)` makes sense as a query, but I don't understand the value in trying to run them together. Do those two queries return the expected results?

The aggregation is rendered mostly meaningless if you are also selecting every individual value in the aggregation. Perhaps there should be a more meaningful error message rather than a null return.

What's the difference between `empid` and `empidtag`?

What version of InfluxDB are you running?

**Comment by pranavrajs** [comment]
@beckettsean  Thanks for your reply. 

I've a time series data of visitors who have visited employees. I want to group by employeeid , since it is not possible to group by field , i've added a tag with the same value.  

If i want to get the count of visitors of each employee in last hour , how can i achieve that ? 

Thanks

**Comment by beckettsean** [comment]
@pranavrajs Thanks for the explanation of `empid` vs `empidtag`. I'm not sure you need to store both. If you have it stored as a tag, storing it again as a field contributes little in the way of new functionality, unless you want to perform functions (MEAN, MAX, MODE, TOP, etc.) on the `empid` field.

> If i want to get the count of visitors of each employee in last hour , how can i achieve that ?

`SELECT COUNT(DISTINCT empid) FROM series WHERE time > now() - 10h GROUP BY empidtag,time(1h)` Should be that exact query. It will output 10 buckets of one hour each for every `empidtag` value, with the contents of each bucket being the count of distinct `empid` values in that hour.

**Comment by pranavrajs** [comment]
@beckettsean Thanks for the reply. I thought about this way of solving the issue . I wanted to know the query design pattern, that's why i added an issue here. Thanks for the help.
