### ISSUE TITLE
Will shorter tag name and field name help reduce the database size?

### ISSUE THREAD

**Issue by airyland** [influxdb/influxdb#3554]
I wonder if it's necessary to use shorter name for tags or fileds name?

**Comment by beckettsean** [comment]
Tag keys and values are only stored once, so their length is effectively irrelevant to total storage size.

I believe field keys are also only stored once and referenced by ID rather than the raw string, so field key length should also be irrelevant to total on disk size. I'm asking for confirmation on that.

There are compression fixes coming in 0.9.3 (https://github.com/influxdb/influxdb/pull/3544) that will also reduce the on disk representation.

**Comment by airyland** [comment]
Cool. Thx.

**Comment by beckettsean** [comment]
@airyland I verified that only a field key ID is stored with the point, so there's no meaningful difference in your on-disk data size for large tag keys, tag values, or field keys. Only the size of field values has any impact on the total disk used.
