### ISSUE TITLE
Data point calculation on InfluxDB 0.8.8

### ISSUE THREAD

**Issue by buro1983** [influxdb/influxdb#3577]
Please help me to understand this how influxDB is doing this.
 
select sum(UpstreamBytes), sum(DownstreamBytes) from Usage.Bangalore.Email where time > 1438776272s and time < 1438776512s group by time(1m)  
 
1438776480000	40467	0
1438776420000	76746	0
1438776360000	136182	0
1438776300000	89471	0
1438776240000	69426	0

 
select sum(UpstreamBytes), sum(DownstreamBytes) from Usage.Bangalore.Email where time > 1438776392s and time < 1438776512s group by time(1m)
 
1438776480000	40467	0
1438776420000	76746	0
1438776360000	31138	0
 
 
1.	I am asking time > 1438776392s and time < 1438776512s but returning data point at 1438776360 which is out of the range
2.	How there are two different values for same data point 1438776360000 .

**Comment by beckettsean** [comment]
The time restriction limits the points returned and summed, but the GROUP BY clause determines the bucket timestamps.

For the first statement, all points from 1438776360000 to 1438776419999 are included in the bucket labeled 1438776360000, and their sum is 136182.

For the second query, the bucket timestamp is still 1438776360000, because you are grouping by minute, but the points included only range from 1438776392000 to 1438776419999. The sum is less because all the points from 1438776360000 to 1438776391999 are excluded from the sum in the second statement.

It's not returning a data point at 1438776360 , it's naming the bucket for the even minute boundaries. I'm not that familiar with 0.8.8, but it seems as though the bucket timestamps don't start at the first valid point in the range, but instead on the nearest minute boundary that contains the first point in the range.
