### ISSUE TITLE
[0.9.3] Poor Performance

### ISSUE THREAD

**Issue by Jhors2** [influxdb/influxdb#3609]
I am currently running version 0.9.3, I know distributed query support is in the works so I hesitated and filing this issue, however the query performance has become very poor.

Currently I have a data set of a million points with this measurement name, it is in it's own retention policy FWIW.

The query takes about 3-4 minutes with the following query:

`SELECT sum(value) from shortLived.as_path_bps WHERE time > now() - 1d AND as_path_list =~ /(.*_|^)16348(_.*|$)/ AND as_path_list !~ /645../ AND pop =~ /mia01/ AND value > 100000000 group by time(1m),as_path_list, pop`

Various ways to implement the above query can make it faster.  One of them is to use a larger group by time to downsample the data.  One is to use a smaller time window.  We've gotten to the point where using a 4d time window can take 10+ minutes to return data.  My question is, is there something that can be done server side to improve this, or is there something I can do with my data post to improve this.

Sample data write:
`as_path_bps,as_path_list=16348_1221_4356_1652_1438_1984,pop=mia01,protocol=ipv4 value=123898912938 /epoch timestamp in ms/`

Would it be helpful to write as_path_list into one tag per digit?  Any input here would be greatly appreciated :)

I'll also note that I have gotten queries that take so long that writes begin to 500, with no other error/debug output in the logs.  However this can be discussed separately.

**Comment by beckettsean** [comment]
> One of them is to use a larger group by time to downsample the data. 

That shouldn't make any noticeable difference in the runtime. It will reduce the number of buckets returned, but the query still has to sample every possible point in the time range and then sum all the matching points. Whether it sums them in 1 minute or 30 minute intervals makes little practical difference.

> One is to use a smaller time window.

Yes, this is the only thing that will have a significant effect on your query performance. There's a field in your WHERE clause (`value`) and fields are unindexed. When there is a field in the WHERE clause every point in the measurement that matches the other filters has to be read from disk. By shrinking your time window, you will narrow the number of points to be sampled and increase the performance of the query.

As for secondary things you can do, one recommendation is to stop using `pop =~ /mia01/` and just state that filter as `pop = 'mia01'`. Equalities evaluate faster than regex matchers. The equality statement can be evaluated directly from the tag set index. The regex iterates over every series in the index looking for matches.

> Would it be helpful to write as_path_list into one tag per digit?

Yes, that would be helpful. As mentioned above, regex matches are more expensive than straight equalities. It's the difference between getting a direct index lookup and iterating over every value in the index. The index of series likely isn't too big, but with three regexes that three iterations over every series rather than a simple index lookup for two of the three. 

The regex lookups are not the primary source of the delay. The field in the where clause means every point has to be read from disk, and that's certainly the biggest bottleneck, but these other effects may contribute as well. I can't say if it would be 1% or 0.01% of the query time, but I would guess it's closer to either of those numbers than to 10%.

> I'll also note that I have gotten queries that take so long that writes begin to 500, with no other error/debug output in the logs. However this can be discussed separately.

There are a number of open issues about this and the read/write locking behavior is substantially changed for 0.9.3.

**Comment by Jhors2** [comment]
Implemented all of the above, we need quite a bit more data to do true side by side comparison but I REALLY appreciate you taking the time to explain and validate my thinking.
