### ISSUE TITLE
[0.9.3] Writing points in the past results in excessive shard precreation

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#3722]
Since writing data into the past is not a relatively important use case, this may not be a huge issue.

If data is written into the past, a shard is naturally created on demand for that shard. Shard precreation will then start pre-creating shards for this shard group, as the end-time of the shard is always less than "now" plus the "advance period". This shard creation will continue until shard have been created to fill in all time from the data written into the past until caught up with "now".

cc @DanielMorsing

**Comment by beckettsean** [comment]
The challenge is differentiating between a new database with backfilling data, where shard precreation makes sense, and a database with a single old point or an inadvertent old timestamp, where shard precreation is not helpful.

I don't have a clean way of differentiating, although probably shard precreation shouldn't operate more than two time windows either side of current points.

**Comment by otoolep** [comment]
@beckettsean -- exactly. @DanielMorsing and I are were discussing this, and detecting the difference between a one off point, and someone actually streaming into the past is difficult. It also occurred to me that the system could check if the shards contain data. The issue with that approach however is that precreation logic runs entirely within the meta cluster code, and has no direct access to the actual data. Shard precreation is purely a meta operation.

**Comment by beckettsean** [comment]
Shard creation is an optimization for performance, so that there's not a big pause when the group time rolls over and the new shards have to be created.

For historic data, there's no triggering event for a bunch of new shards to be created, except that new data with old timestamps keeps coming in. Since writing historical data is not the most common use case, and since shard precreation is an optimization, not a requirement, perhaps we should disable precreation of shards older than the current day? That's not elegant at all but would mitigate this particular issue. Users writing lots of data to the past will see performance blips on the shard boundaries but there should be no reason why the write path backing up is a problem in those cases, as the data is not real-time.

**Comment by otoolep** [comment]
@beckettsean -- that sounds reasonable, and I would be happy with that approach. Of course, we can make it a config flag, and have creation of shards with start and end-times completely in the past be disabled by default.

**Comment by beckettsean** [comment]
Talked with @pauldix, just disable shard precreation for any time in the past.

**Comment by pauldix** [comment]
Yeah, this is a bug. Shard pre-creation should only be for a shard that is about to be `now`. This is how this used to work.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/3931

**Comment by otoolep** [comment]
All fixed for 0.9.4.
