### ISSUE TITLE
Should log an error if Graphite TCP listener times out on read

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#3739]
See this section: https://github.com/influxdb/influxdb/blob/master/services/graphite/service.go#L184-L187

If we timeout on the read, we should log the error.

**Comment by otoolep** [comment]
This requires setting the read timeout on the connection, working started https://github.com/influxdb/influxdb/pull/3771

**Comment by pauldix** [comment]
We had reports that they were timing out. Maybe they were actually timing out on the client side?

**Comment by pauldix** [comment]
Do we actually want to timeout the TCP connection? Not sure that we do since it's supposed to be long lived.

**Comment by otoolep** [comment]
If we got reports, it must have been a client-side thing since the TCP connections do not currently time out, and I thought that is what you're asking for.

On other servers I've written, there is an close-after-idle time (to free up resources), which is what the associated PR is about. If we don't want this, I can close the PR.

**Comment by pauldix** [comment]
probably a good idea, but we'll have to document it

**Comment by otoolep** [comment]
Not sure if we want the patch in 0.9.3, it's not huge value right now and it might be better to have it soak.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/pull/3771 reading for review.

**Comment by otoolep** [comment]
We decided against implementing the timeout, so closing.
