### ISSUE TITLE
Missing tags during select in influxdb_0.9.3-rc1

### ISSUE THREAD

**Issue by buro1983** [influxdb/influxdb#3757]
Issue: Tags are missing in 0.9.3-rc1 release during select, where as it is working on 0.9.2

=====

Steps to reproduce:

================

1) insert :  `curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu_load_short,host=server01,region=us-west value=0.64'`
2)  select * from cpu_load_short

Output on 0.9.3-rc1:
```
{
    results: [
    {
        series: [
        {
             name: "cpu_load_short",
             columns: [
                   "time",
                   "host",
                   "region",
                   "value"
              ],
              values: [
                  [
                        "2015-08-20T11:33:06.521791348Z",
                        "server01",
                        "us-west",
                         0.64
                  ]
               ]
            }
         ]
      }
   ]
}
```

Output on 0.9.2:
```
{
      results: [
      {
             series: [
             {
                     name: "cpu_load_short",
                     tags: {
                             host: "server01",
                             region: "us-west"
                      },
                      columns: [
                              "time",
                               "value"
                      ],
                      values: [
                            [
                                   "2015-08-20T11:52:57.85384834Z",
                                    0.64
                            ]
                      ]
               }
              ]
         }
     ]
}
```
Am I missing something?

**Comment by otoolep** [comment]
@corylanou -- was this part of the work you did?

**Comment by corylanou** [comment]
This is the correct behavior.  In `0.9.2` there was an implicit `GROUP BY *` on every `SELECT *` that didn't have a specified `GROUP BY`.

To get the same behavior as `0.9.2` in `0.9.3` you can issue this query:

`SELECT * from cpu_load_short GROUP BY *`

and it will give you tags.

If you issue the following:

`SELECT * FROM cpu_load_short`

the tags come back as `columns` in your results just like fields.

@otoolep we need to make this very clear in our release notes for `0.9.3`

**Comment by otoolep** [comment]
Done @corylanou https://github.com/influxdb/influxdb/commit/fa01abf3c992cb6b3e048c8d855de51815b36171

**Comment by otoolep** [comment]
Closing as correct behaviour for 0.9.3.

**Comment by pauldix** [comment]
I should provide a bit more of an explanation on why we did this. It was causing a problem because there were many cases where people wanted to do a `SELECT *` but they didn't want to do a corresponding `GROUP BY *`. Having that rewrite was causing a bunch of weird behavior for people.

Sorry about the change, we're hoping that it will actually enable more query functionality than was possible before.

**Comment by buro1983** [comment]
Problem will  be if your application is aligned with 0.9.2 then it will not work with 0.9.3. If anyone want to upgrade Influx 0.9.2 to 0.9.3 then they need to change application code too. Please provide a detail information how it will improve overall product performance.

**Comment by pauldix** [comment]
@buro1983 yes, unfortunately, it's a breaking change to the API. We really didn't want to make any, but felt it was better to get this done sooner rather than later. I also made an assumption that most people issuing `SELECT *` queries, were actually doing so from the CLI since it would be more common in code to actually select the columns you want explicitly.

This change wasn't about performance, it was about usability. Also, there were bugs that were introduced by automatically rewriting the query to `GROUP BY *`.

**Comment by buro1983** [comment]
Thanks for the update. I will keep you guys posted if I observe any more issues
