### ISSUE TITLE
[feature request] rename "influx" to "influx-cli"

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#3855]
It's confusing for some users whether `influxd` or `influx` is the right process to launch. Running `influx` before `influxd` leads to confusing results.

I propose we rename `influx` to `influx-cli` to make it clear what the binary does, and to reduce the chance that the two can be mis-read in documentation.

**Comment by otoolep** [comment]
+1

**Comment by beckettsean** [comment]
I'm not sure if this counts as a breaking change or not. I tend to think not, since libraries shouldn't be relying on `influx` but instead calling endpoints directly.

**Comment by otoolep** [comment]
We could have packaging create a symlink so that both `influx` and `influx-cli` appear after installation. `influx` would be the symlink, and all documentation would be updated to `influx-cli`. At some time in the future (soon hopefully) we'd stop creating the `influx` symlink.

**Comment by pauldix** [comment]
+1

**Comment by corylanou** [comment]
@otoolep I think the symlink would bring us back to the same exact issue as to why we are changing the name in the first place.

**Comment by otoolep** [comment]
@corylanou -- the symlink is about easing the transition and allowing us to mark `influx` as deprecated.  Then we warn people the change is coming soon. Or am I missing your point?

**Comment by corylanou** [comment]
@otoolep as long as it's to make a transition.  Maybe instead of a symlink we do a script that echos it is going to be deprecated and to use the `influx-cli`, then launches `influx-cli`.

**Comment by otoolep** [comment]
@corylanou -- not a bad idea, would definitely help.

**Comment by beckettsean** [comment]
I don't want a symlink. If I just installed something called "InfluxDB" and there's an `influx` symlink, 99 out of 100 will assume that symlink starts the actual database.

A script is a nice solution, +1

**Comment by zimbatm** [comment]
-1 It's a common scheme in the unix world. Eg: `mysql` and `mysqld`. It's better to improve the error message if influxd is not reachable.

**Comment by beckettsean** [comment]
@zimbatm the proposed change actively helps a number of users who are confused. Does it actively hurt your use case or understanding?

**Comment by zimbatm** [comment]
It's quite a minor thing but I think the reason of the original naming is so that tab-completion would resolve to the client by default. Operationally speaking it's really rare to execute the daemon by hand by less so the client. If the client is renamed to `influx-cli`, `inf<tab>` won't resolve to it anymore.

For me learning the difference between `influx` and `influxd` is a one-time thing and can be re-applied to other services, vs potential lots of tab-completions during development and operations.

**Comment by beckettsean** [comment]
@zimbatm that is a good point. Good enough to make me reconsider, but I'm not sure I've changed my mind. @pauldix or @otoolep, thoughts?

**Comment by otoolep** [comment]
I've been thinking a little bit about this in recent days. There is precedent for what we are doing now:

- mysql and mysqld
- sqlite (it's not sqlite-cli)
- mongo and mongod (I believe)

So perhaps we are going to far here. I think this originally bugged me because tab completion within the source tree kept sending me into the wrong directory (I wanted to go into `influxd`). But that is a developer-only concern, so not a user concern.

I think we should hold off on this for now.

**Comment by corylanou** [comment]
I agree, I think what we have is following what others are used to, and I don't really have a better solution.

**Comment by beckettsean** [comment]
Closing in favor of https://github.com/influxdb/influxdb/issues/3894

**Comment by beckettsean** [comment]
Thanks, @zimbatm!

**Comment by zimbatm** [comment]
:+1:

**Comment by pauldix** [comment]
agree, good call
