### ISSUE TITLE
[feature request] Insert new tags to existing values, like update

### ISSUE THREAD

**Issue by mvadu** [influxdb/influxdb#3904]
Can we have a query syntax which allows to insert/attach a new set of tags (along with exiting ones) to values/rows that are already part of a measurement?

My use case: I created a measurement from PerfMon log, which already has Host=<server name> tag. Now I want to categorize the data by applications, so I want to add tags like "App1=<app name>, App2=<app name>" assuming I can have two apps hosted on same server. 

Then I want to be able to say `Update <measurement name> add <tag name=value> where <some condition based on tags>`

**Comment by airyland** [comment]
+1

**Comment by beckettsean** [comment]
This feature would require a fairly major architectural change to the database and is not something we will do this year, if ever. Closing the request for now.

**Comment by mvadu** [comment]
Please consider this during your next architecture review. I think this would be required in many enterprise  situations, where you f**k up while inserting values, and realize it later. Having an option ti update would be a life saver!

**Comment by ivanscattergood** [comment]
Hi, 
I have been two specific use cases for this functionality

1) Obfuscation of data for testing / demo purposes. 
As the data we deal with is Market data the Tags within the data may actually refer to a ticker and given the other attributes of the data you can work out trade information. I am currently working on a data set which I have been asked to Obfuscate for a demo. To achieve this I am currently loading the dataset into memory and writing it back in with new tags. (This would be simplified by the insert into functionality that has been proposed in #211)

2) Change of the Tag value in the real world
Imagine that one of the tags in your data referenced the Name of a department, if that department name changed it would be good to be able to change it historically, rather than having to have the two tag values running in tandem. 
In the world of Data Warehousing this is known as slowly changing dimensions: 
http://datawarehouse4u.info/SCD-Slowly-Changing-Dimensions.html

**Comment by rapport** [comment]
+1 For us events are usually only recognising in the data following a reasoning step after capture. And, we want to tag data with its event once its recognised. I am considering using continuous queries to do some of this tagging after capture but it seems inefficient and I am not sure it will work for all our use cases

**Comment by srikara** [comment]
+1

**Comment by mrh666** [comment]
+1
This is will be surprisingly useful feature! Sometimes our developers sending metrics not following the namespace requirement, but following some pre-defined hardcoded application name structure (storm metrics collector for example) and those metrics have a lot of value for research.

**Comment by jarlwolfganger** [comment]
+1, if you guys aren't going to add this in some time soon could you at least add work around options to the current documentation since there was nothing mentioning appending tags to an existing measurement.

**Comment by open-homeautomation** [comment]
+1 this is definitely needed in many real-world solutions as architectural changes might need additional tags.

**Comment by hgomez-sonarsource** [comment]
+1 to add this feature since as of today, there is no other options than to dump a measure in ASCII, hack ASCII file and send it back to a new measure via wireprotocol.

**Comment by moltenkaizen** [comment]
+1

**Comment by hgomez-sonarsource** [comment]
For now, I updated my InfluxDB Fetcher tool (https://github.com/hgomez/influxdb) to transform fields in tags so I could reimport them in proper format

**Comment by jincejames** [comment]
+1

**Comment by szll** [comment]
+1

**Comment by autumnw** [comment]
+1

**Comment by andreaaizza** [comment]
+1

**Comment by ryanmills** [comment]
+1 please provide ability to update existing tags

**Comment by geethanjalieswaran** [comment]
+1

**Comment by mvadu** [comment]
@beckettsean Hi Sean, since closing this request quite few folks have expressed their interest and support for this feature. Do you guys want to reconsider this request?

**Comment by ryanmills** [comment]
Another use case is that deletes are expensive so you could update a tag to mark the record as active/disabled instead of deleting it and include the status tag in the query.

**Comment by hcsaustrup** [comment]
+1

**Comment by hraftery** [comment]
Issue https://github.com/influxdata/influxdb/issues/828 concerns renaming databases, measurements,  fields and tags. Some of that functionality is provided by `INTO`. Eg.
`SELECT "old_field_key" AS "new_field_key" INTO new_db..new_measurement FROM old_db..old_measurement GROUP BY "old_tag_key"`
renames database, measurement and field key, but cannot be extended to rename the tag key or update with new tags.

Given those limitations, it may be better to dump data, convert to line protocol, go nuts with sed to change/add keys, and then POST back.

@hgomez-sonarsource 's excellent [InfluxDB Fetcher](https://github.com/hgomez/influxdb) makes this quite quick and easy, but note:

- It requires maven and java. Easy to install and use, but requires quite a few packages to be downloaded/built/tested/installed.
- The invocation line is long and complex, but works just fine if you're careful.
- The extra "data1,data2" arguments are for converting a tag to a field, so don't do anything if you don't have fields by those names. You can achieve the same in your sed script anyway.
- You probably don't want the 'i' (integer) suffixes on your values because Influx numeric fields are floats by default, so make sure you strip them out in your sed script.

So you can do a simultaneous database rename, measurement rename, field rename, tag rename and tag addition with three lines:

```
java -cp target/influxdb-fetcher-1.0.0-SNAPSHOT.jar com.github.hgomez.influxdb.InfluxDBFetcher http://127.0.0.1:8086 login password old_db "SELECT * from old_measurement GROUP BY *" > dump.wireproto
sed -i -e "s/old_measurement/new_measurement/;s/old_field_key/new_field_key/;s/old_tag_key/new_tag_key/;s/new_tag_key/additional_tag_key=additional_tag,new_tag_key/;s/i,/,/g;s/i / /" dump.wireproto 
curl -i -POST "http://127.0.0.1:8086/write?db=new_db" --data-binary @dump.wireproto
```

YMMV

**Comment by andyflury** [comment]
+1

**Comment by hraftery** [comment]
Just came across a possible improvement on my workaround posted above. Haven't investigated it, but `influx_inspect export` might be a replacement for InfluxDB Fetcher for this purpose?

**Comment by einhirn** [comment]
@hraftery Nice, but you can only use it on database level, not measurement level. Output will get very big, very soon, and I didn't manage to have it output to stdout (i.e. pipe.). Of course you can work around that with mkfifo etc. but still big output...

**Comment by vikrammurugesan** [comment]
+1 this will be really useful feature

**Comment by runner-mei** [comment]
+1, this will be really useful feature for refact app

**Comment by samhatchett** [comment]
+1 : this could also be accomplished if `SELECT INTO ` could alter or replace tag keys/values.

**Comment by raidsan** [comment]
I google "influxdb add tag" and get here,  now I decidid to go back to use postgresql.

**Comment by Vistritium** [comment]
+1, I need this.

**Comment by j-wil** [comment]
+1

**Comment by mvadu** [comment]
I wanted a light weight part to do what @hgomez-sonarsource 's excellent InfluxDB Fetcher (with [few drawbacks](https://github.com/influxdata/influxdb/issues/3904#issuecomment-268918613)) does. So I wrote a simple extractor in Powershell. https://github.com/AdysTech/ExtractTransformInflux/blob/master/ExtractTransformInflux.ps1 gets the job done..

**Comment by carlospenedorocha** [comment]
+1

**Comment by tcloaa** [comment]
In the documentation of v1.2, it is stated that: "InfluxDB is a schemaless database which means it’s easy to **add new measurements, tags, and fields at any time**. It’s designed to make working with time series data awesome."

But there aren't any reference/API for me to do this from the documentation...

Faint

**Comment by vhdmsm** [comment]
+1

**Comment by davweiss** [comment]
+1

**Comment by baoyicai** [comment]
+1

**Comment by ckatsulis** [comment]
+1

**Comment by JeffAbrahamson** [comment]
+1

**Comment by meesern** [comment]
+1  to allow tagging measurements with post processed tags.

**Comment by amoondra19** [comment]
+1

**Comment by bkdonline** [comment]
@beckettsean Can this be reconsidered at this point? Its been two years since the thread was closed, and it might be more feasible architecturally to consider this now!

This will be extremely useful for maintaining data in medium to long term in an enterprise setting.

**Comment by GerbenWijnja** [comment]
+1
Just realized that a CQ by default drops all tags during while it downsamples data. The tags in the source table were always the same (network traffic for 1 host, 1 interface), so I never noticed the missing tags in the downsampled table. Now that I'm adding a second host, I realize that all existing downsampled entries need to have the tags added (the same for all entries) before I can add a new host.

**Comment by gylu** [comment]
+1
Having to query out and then rewrite every single data point to rename a tag is not very efficient

**Comment by UVk** [comment]
+1

**Comment by rvolosatovs** [comment]
Encountered this issue on a production system. We have around a million entries every day, the current dataset has been accumulating for half a year.
I was going to set up some additional continuous queries, but turned out that is not possible, as some of the values in measurements, which I wanted to `GROUP BY` are stored as fields and there is not way to group by "field" types and also no way to convert the "field" types to "tag" types.

Work has been started on a simple [utility](https://github.com/rvolosatovs/influx-taggify) to convert fields to tags in the wire protocol representation.
```sh
go get -u github.com/rvolosatovs/influx-taggify
```
Example usage:
```sh
influx_inspect export -database "$db" -datadir "$datadir" -waldir "$waldir" -out /tmp/influx-export
# Delete the measurements you don't need to convert using `sed`/`perl` (i.e. `perl -in -e 'print unless m/^unrelated_measurement.*/' /tmp/influx-export`)
influx-taggify -in /tmp/influx-export -out /tmp/influx-export-tagged fieldFoo fieldBar
# Drop the old database or edit generated file to change the name of the database
influx -import -path /tmp/influx-export-tagged
```
It worked for my use case, but your mileage may vary.
Try locally on non-critical setup first!
Feel free to try, report issues and contribute! :)

**Comment by YeisonMelo** [comment]
+1 @2018

**Comment by jheusser** [comment]
+1

**Comment by JavierGarciaD** [comment]
+1

**Comment by HyEvil** [comment]
+1

**Comment by kikohs** [comment]
+1

**Comment by galindro** [comment]
+1

**Comment by hraftery** [comment]
For what it's worth I've revisited this 2 years later and explored all alternative options for exporting/importing data. To save others the hours of frustration, it seems my [workaround](https://github.com/influxdata/influxdb/issues/3904#issuecomment-268918613) above is still the easiest way to achieve this and all manner of related export/import tasks.

Lesser alternatives:

- The `influx_inspect` tool is complicated, requires sudo, relies on TSM files and dumps the whole db.
- The HTTP API (eg. via curl) is great, but it produces JSON **that can't be read by influx**!
- The `influx` tool's `- execute` flag is promising, but even `csv2influx.py` can't read the csv generated.

**Comment by samhatchett** [comment]
We were trying to solve this problem for a customer - where data may have been inserted incorrectly and we then needed to go back and re-tag a series (or several series). We ended up creating a little node-based migration service. It's solving our problem for now, and our customer has a more friendly means of managing their data. May not be suitable for all cases. You can find it [here](https://github.com/CitiLogics/datalyzer-measurement-migration-microservice).

**Comment by steverweber** [comment]
```
+1 : this could also be accomplished if SELECT INTO could alter or replace tag keys/values.
```
this would be nice in `CONTINUOUS QUERY`... because the data is being transformed and new tags would be the most logical.

example:

we have a few lab room and we use a CQ to find how busy each room is...
it be ideal if we could tag the room like mc3006... but because of influxdb current limitations we are using a new metric for each one.
```
SELECT sum("value") INTO "thinclient_active_mc3006" FROM "thinclient_active" WHERE ("host" =~ /3006/) GROUP BY time(1m, -5m)
SELECT sum("value") INTO "thinclient_active_mc3007" FROM "thinclient_active" WHERE ("host" =~ /3007/) GROUP BY time(1m, -5m)
SELECT sum("value") INTO "thinclient_active_mc3008" FROM "thinclient_active" WHERE ("host" =~ /3008/) GROUP BY time(1m, -5m)
```

something like the following would would be a nice improvement!
```
SELECT sum("value"), room::tag=mc3008 INTO "thinclient_active_room" FROM "thinclient_active" WHERE ("host" =~ /3008/) GROUP BY time(1m, -5m), room
```

**Comment by steverweber** [comment]
@hraftery please reconsider this issue.

**Comment by hraftery** [comment]
@steverweber I'm just a user - you probably want to direct your request to a contributor. But I wouldn't hold your breath. This issue was closed back in [2015](https://github.com/influxdata/influxdb/issues/3904#issuecomment-136846111). There are at least three workarounds described in this thread, but I agree, something along the lines of a `SELECT INTO` would be far better.

**Comment by snenkov** [comment]
I sincerely with that this would be reconsidered. It's a must-have :)

**Comment by kaszperro** [comment]
Are there any plans to implement this feature in influxdb 2.0?

**Comment by kavinbright** [comment]
+1

**Comment by amotl** [comment]
Hi there,

following up on the comment by @hraftery at https://github.com/influxdata/influxdb/issues/3904#issuecomment-268918613, everything about @hgomez' excellent [InfluxDB Fetcher](https://github.com/hgomez/influxdb) still holds true, but we just improved the convenience of installation.

You don't have to build it yourself from now on but instead you can conveniently download a ready-made [`influxdb-fetcher-1.0.2.jar`](https://github.com/hgomez/influxdb/releases/download/1.0.2/influxdb-fetcher-1.0.2.jar) to your workstation. The new setup instructions at [1] outline how to easily install a wrapper program which will download the .jar file automatically on its first invocation.

With kind regards,
Andreas.

[1] https://github.com/hgomez/influxdb#setup
