### ISSUE TITLE
[feature request] Ability to drop tags for a database

### ISSUE THREAD

**Issue by robinjha** [influxdb/influxdb#3911]
We have a requirement where we would need to update/delete tags for a database. Could you please provide us with an ability to do that? 

This would prevent drop-down menus to be populated with older tags which no longer has data associated with it.

**Comment by beckettsean** [comment]
`DROP SERIES` will do what you describe. For example:

`DROP SERIES FROM my_measurement WHERE mytag = 'valid_tag_value'`

The equality in the WHERE clause will not accept a regular expression, so you will need to explicitly drop the series for each tag key-value pair, rather than being able to drop all series for a given tag key with a single query.

**Comment by robinjha** [comment]
Thanks Sean! I will give this a try.

**Comment by andyxning** [comment]
@beckettsean Will Influxdb delete empty value tags  automatically when its time is beyond the retention policy?
