### ISSUE TITLE
Templates not being applied

### ISSUE THREAD

**Issue by matejzero** [influxdb/influxdb#3920]
Hello,

I'm doing some tests with InfluxDB and I'm not sure if I'm doing something wrong or if this is a bug.

So, I have a metric in collectd: 
```
servers.test_domain_com.load.load.shortterm
```
I set up my template as: 
```
"*.load.load.* env.host.plugin.measurement*"
```

I load InfluxDB and send a test metric to database:
```
echo "servers.test_domain_com.load.load.shortterm 2 $(date +%s)" | nc  -u localhost 3003
```

When I look at the data in database, I get the following:
```
> show series
name: servers.test_domain_com.load.load.shortterm
---------------------------------------------------
_key
servers.test_domain_com.load.load.shortterm
```
Should it work like that? Does a wildcard `*.load` match "everything before load" or does it match one metric before load?
If latter, what would be the correct way to write a filter: `*.*.load.*`?

Also, it is possible to drop a certain tag?
In a metric `servers.test_domain_com.load.load.shortterm` I would like the following output, dropping one `load` field:
```
> show series
name: load_shortterm
--------------------
_key								                           env	 host			
load_shortterm,env=servers,host=test_domain_com	servers	test_domain_com
```

Another example is interface plugin for collectd:
Metric: `servers.text_example_com.interface-ens192.if_packets.tx`
What I want:
```
name:tx
env: servers
host: text_example_com
plugin: interface-ens192 (it would be even nicer, if I could have plugin:interface and if:ens192)
type: if_packets
```

Anything of this possible?

**Comment by jwilder** [comment]
For filters, you need a wildcard or value for each component of the metric.  What is happening in you case is that the metric:
```
servers.test_domain_com.load.load.shortterm
```

With filter and template:

```
*.load.load.* env.host.plugin.measurement*
```

is not matching and the full metric name is used as the measurement name.  That is the default behavior when no templates match.  To make the template match this measurements, you need one more `*` at the front:

```
*.*.load.load.* env.host.plugin.measurement*
```

To answer you question about the wildcard prefix matching, no, a `*` at the front does not match all elements up to `load`.  What it means is that value at that part of the metric name can be anything.  It uses the `.` to match up values when filtering.

Using the template above, you would get:
```
> show series
name: load.shortterm
--------------------
_key								env	host		plugin
load.shortterm,env=servers,host=test_domain_com,plugin=load	servers	test_domain_com	load
```

If you want to drop the `load` prefix, use:
```
*.*.load.load.* env.host.plugin..measurement*
```

Note the additional `.` after plugins.  The template matches that value but since there is no tag name defined, it drops it from the tags.   Using this template, you would get:
```
name: shortterm
---------------
_key							env	host		plugin
shortterm,env=servers,host=test_domain_com,plugin=load	servers	test_domain_com	load
```

You can also add additional tags with something like:
```
*.*.load.load.* env.host.plugin..measurement* collector=collectd,region=us-west
```

which would give you:
```
name: shortterm
---------------
_key												collector	env	host		plugin	region
shortterm,collector=collectd,env=servers,host=test_domain_com,plugin=load,region=us-west	collectd	servers	test_domain_com	load	us-west
```

For your last use case, you could use:
```
*.*.*.if_packets.tx env.host.plugin.type.measurement
```

Which would give you:
```
ame: tx
--------
_key										env	host			plugin			type
tx,env=servers,host=test_example_com,plugin=interface-ens192,type=if_packets	servers	test_example_com	interface-ens192	if_packets
```

You can't currently split the tag value for `interface-ens192` as you described but if you know all the interfaces you have, you could add them as additional tags and drop the metric value with something like:

```
*.*.interface-ens192.if_packets.tx env.host..type.measurement plugin=interface,if=ens192
```

That should get the metric formatted the way you wanted.

**Comment by matejzero** [comment]
Hey there,
thanks for all the answers. It will really help me tomorrow finish up the configuration.

I guess only one problem exists and that is the splitting of the interface. Unfortunately I don't know all the interfaces, since they are different on different servers and the way that collectd send the metrics, they are named like this. 
Diamond is superior in this case, since his metrics name is env.host.interface.ifname.iferror.rx which is easier to parse and then query. It looks like I will have to run another service in-front and do a metric renaming or something...
Is it possible to use regex in tags definition?

Matej

**Comment by jwilder** [comment]
No problem.  There is no way to use a regex or split the values on any char at the moment.  If you want to log a feature request with your sample data and what you are trying to achieve that would be great.

**Comment by matejzero** [comment]
Just in case someone comes along the same problem, I solved it with the use of another collectd plugin (write_opentsdb). There is currently a pull request, but its stable and I expect it to be merged to master soon.
