### ISSUE TITLE
Add clarification of intended behaviour for Graphite input templates with *no* default template

### ISSUE THREAD

**Issue by noroute** [influxdb/influxdb#4032]
There is no test and no example I can find for the Graphite input plugin templating functionality without any default templates. The intuitively expected behaviour is to ignore measurements that don't match any template.

What happens is (ignore-unnames is 'false') that when there is no default template, the whole metric name ('foo.bar.baz') is recorded. When I add a default with just "measurement" (no filter) the first part of every metric is recorded as a measurement but only contains a series with one entry (value == 0).

What would I do if I'd like to just drop measurements that don't match any of the templates?

**Comment by jwilder** [comment]
The default behavior when there is no default template specified is to use the full metric name as the measurement.  It is described here: https://github.com/influxdb/influxdb/tree/master/services/graphite#introduction and it is essentially `measurement*`.  It works that way so that you are not required to define templates to get up and running  quickly.  If you choose to add filters and templates, you can extract measurements and tags.

There is currently no way to drop measurements.  `ignore-unnames` is not a valid config option.

**Comment by beckettsean** [comment]
@noroute, given @jwilder's feedback it sounds like this is more a feature request for "I'd like to just drop measurements that don't match any of the templates". Is that true?

**Comment by noroute** [comment]
@beckettsean Yes, that's what I meant. It's not terribly important at the moment, I now get the rationale for the current implementation. Will provide a PR for the Graphite plugin documentation to clarify template defaulting (as explained by @jwilder).

Thanks for clarifying.

**Comment by beckettsean** [comment]
@noroute would it be okay with you if we close this issue and wait for your PR?

**Comment by noroute** [comment]
@beckettsean Sure. Sorry for taking so long to reply.
