### ISSUE TITLE
why can't write the data with same timestamp(nanosecond) and same kv pair?

### ISSUE THREAD

**Issue by harryshayne** [influxdb/influxdb#4080]
why can't write the data with same timestamp(nanosecond) and same kv pair?for example,write data like this twice:
test,host=server02,region=us-west value=0.12 1422568543702900257
test,host=server02,region=us-west value=0.12 1422568543702900257

in influxdb0.8,it's ok,diff this two with seq number, but in influxdb0.9, can't do,without seq number.

**Comment by pauldix** [comment]
This is by design in 0.9. If you need two points with the same nanosecond timestamp, create additional series by adding tags. For your example, it's not legitimate to have two data points at the same timestamp since they'd either be identical values, or different values (which would be impossible because you'd have a sensor reporting two different values for the exact same moment in time).

**Comment by harryshayne** [comment]
Got it ! Thx !
