### ISSUE TITLE
[0.9.4-rc1] Default WAL settings causing write timeouts

### ISSUE THREAD

**Issue by KiNgMaR** [influxdb/influxdb#4096]
Some flushes from a low-traffic database:

    [wal] 2015/09/14 08:50:09 Flush due to idle. Flushing 14 series with 27 points and 459 bytes from partition 1
    [wal] 2015/09/14 08:50:09 write to index of partition 1 took 9.622795ms
    [wal] 2015/09/14 08:50:19 Flush due to idle. Flushing 1 series with 1 points and 17 bytes from partition 1
    [wal] 2015/09/14 08:50:19 write to index of partition 1 took 5.204475ms
    [wal] 2015/09/14 08:50:34 Flush due to idle. Flushing 15 series with 15 points and 255 bytes from partition 1
    [wal] 2015/09/14 08:50:34 write to index of partition 1 took 3.627889ms
    [wal] 2015/09/14 08:50:44 Flush due to idle. Flushing 19 series with 19 points and 323 bytes from partition 1
    [wal] 2015/09/14 08:50:44 write to index of partition 1 took 6.762247ms

After 24 minutes of uptime, the WAL from the big database is being flushed:

    [wal] 2015/09/14 08:50:53 Flush due to memory. Flushing 327206 series with 1234168 points and 20980856 bytes from partition 1
    [wal] 2015/09/14 08:50:54 Flush due to idle. Flushing 31 series with 34 points and 578 bytes from partition 1
    [wal] 2015/09/14 08:50:54 write to index of partition 1 took 3.052655ms

1234168 points in 24 minutes equal 900 points per second - which is not really a lot?

Now, timeouts start to appear:

    [udp] 2015/09/14 08:51:02 failed to write point batch to database "xxx_prod": timeout
    [wal] 2015/09/14 08:51:05 Flush due to idle. Flushing 5 series with 16 points and 272 bytes from partition 1
    [wal] 2015/09/14 08:51:05 write to index of partition 1 took 2.245901ms
    [udp] 2015/09/14 08:51:07 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 08:51:12 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 08:51:17 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 08:51:22 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 08:51:27 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 08:51:32 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 08:51:37 failed to write point batch to database "xxx_prod": timeout

That continues until the flush operation is complete:

    [wal] 2015/09/14 08:53:23 write to index of partition 1 took 2m30.416279098s

For now, I reduced wal-partition-size-threshold to 600000. This seems to be a good number for my setup. Flushes now complete in 2-5 seconds.

    [wal] 2015/09/14 09:26:46 Flush due to memory. Flushing 24499 series with 38244 points and 650148 bytes from partition 1
    [wal] 2015/09/14 09:27:21 Flush due to memory. Flushing 27640 series with 44482 points and 756194 bytes from partition 1
    [wal] 2015/09/14 09:27:51 Flush due to memory. Flushing 24657 series with 39907 points and 678419 bytes from partition 1
    [wal] 2015/09/14 09:28:21 Flush due to memory. Flushing 24104 series with 38973 points and 662541 bytes from partition 1
    [wal] 2015/09/14 09:28:46 Flush due to memory. Flushing 22132 series with 37176 points and 631992 bytes from partition 1

However, I would like to know whether the flush is IO or CPU bound. Looking at the process statistics, neither seems to be particularly saturated during the flush. Furthermore, InfluxDB does not shut down cleanly while a flush is happening.

**Comment by KiNgMaR** [comment]
After running okay for a while, writes started to fail again also with the updated WAL settings:

    [udp] 2015/09/14 13:10:22 failed to write point batch to database "xxx_prod": timeout
    ...
    [udp] 2015/09/14 13:16:51 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 13:18:32 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 13:20:29 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 13:20:37 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 13:20:45 failed to write point batch to database "xxx_prod": timeout
    [write] 2015/09/14 13:30:48 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:30:48 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:30:53 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:30:53 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:30:58 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:30:58 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:31:04 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:31:04 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:31:08 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:31:08 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:31:13 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:31:13 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:31:18 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:31:18 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:31:23 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:31:23 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:31:28 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:31:28 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:31:33 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:31:33 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:31:38 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:31:38 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:31:43 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:31:43 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:31:48 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:31:48 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:31:53 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:31:53 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:31:58 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:31:58 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:32:03 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:32:03 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:32:08 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:32:08 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [write] 2015/09/14 13:32:13 write failed for shard 2 on node 1: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:32:13 failed to write point batch to database "xxx_prod": write failed: engine: write points: write throughput too high. backoff and retry
    [udp] 2015/09/14 13:32:26 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 13:32:34 failed to write point batch to database "xxx_prod": timeout
    ...
    [udp] 2015/09/14 13:38:55 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 13:39:03 failed to write point batch to database "xxx_prod": timeout
    [udp] 2015/09/14 13:39:11 failed to write point batch to database "xxx_prod": timeout

At this point, influxdb was killed due to OOM. I started it back up a few minutes later.

    [wal] 2015/09/14 13:53:39 reading WAL files to flush to index
    [wal] 2015/09/14 13:53:40 writing 46817 series from WAL file /var/opt/influxdb/wal/xxx_prod/default/2/01.000480.wal to index
    ...
    [wal] 2015/09/14 14:15:14 writing 0 series from WAL file /var/opt/influxdb/wal/xxx_prod/default/2/01.000482.wal to index

After writing from the WAL to the index (which took almost 20 minutes!) it ran okay for about a minute, then crashed with a stack trace due to not being able to allocate memory. The full log file is here: https://gist.github.com/KiNgMaR/b7bb1969acd21225177e

I will of course patiently wait for new storage engine, but am a little surprised that 0.9.x has trouble handling this lite workload where 0.8 did not :)

**Comment by rkuchan** [comment]
@KiNgMaR,
 
We're trying to reproduce your situation. Would you mind sending along your config file and giving some details about your RAM, CPU, and IOPS? Also - how many points per second were you writing and were you running any queries at the time? Thanks!

**Comment by KiNgMaR** [comment]
Hey @rkuchan, thanks for looking into it! I can send the full log file (including [query] entries) via mail (it may contain some "sensitive" data). Which address can I send it to?

Points per second = about 900

System specs:
* VMware 6 virtual machine
* 8 cores (5399.99 bogomips each)
* 16 GB RAM
* CentOS 6.6
* Kernel 2.6.32-504.30.3.el6.centos.plus.x86_64
* nothing else is running on the machine
* the /var/opt/influxdb/data/ directory is mounted via NFSv3 (10 GBit Ethernet, 155 MB/s write throughput according to dd, latency should also be fairly good, https://gist.github.com/KiNgMaR/7440e0369b01e291fed0)

Config file: https://gist.github.com/KiNgMaR/b1232f45a9eb12fa2f8f

Thank you!

**Comment by rkuchan** [comment]
No problem! You can upload your stuff here: https://www.cloudwok.com/cu/gh4096.

**Comment by KiNgMaR** [comment]
Logs uploaded. Thanks!

**Comment by itachi90** [comment]
We see similar issue with stable 0.9.4 release. The write request time out number was more or less a constant for almost one day, and today the time out number begin linearly increasing. 
The log shows points write time out after wal flush:
[wal] 2015/09/18 02:54:05 Flush due to idle. Flushing 23 series with 27 points and 1156 bytes from partition 1
[wal] 2015/09/18 02:54:07 Flush due to idle. Flushing 24 series with 29 points and 1236 bytes from partition 1
[wal] 2015/09/18 02:54:07 Flush due to idle. Flushing 10 series with 10 points and 945 bytes from partition 1
[wal] 2015/09/18 02:54:07 Flush due to idle. Flushing 23 series with 29 points and 1234 bytes from partition 1
[wal] 2015/09/18 02:54:07 Flush due to idle. Flushing 135 series with 158 points and 5549 bytes from partition 1
[wal] 2015/09/18 02:54:07 Flush due to idle. Flushing 70 series with 70 points and 4322 bytes from partition 1
[wal] 2015/09/18 02:54:09 Flush due to idle. Flushing 22 series with 22 points and 1722 bytes from partition 1
[wal] 2015/09/18 02:54:10 Flush due to idle. Flushing 91 series with 199 points and 14040 bytes from partition 1
[wal] 2015/09/18 02:54:10 Flush due to idle. Flushing 35 series with 78 points and 3778 bytes from partition 1
[wal] 2015/09/18 02:54:10 Flush due to idle. Flushing 50 series with 8433 points and 445509 bytes from partition 1
[wal] 2015/09/18 02:54:10 Flush due to idle. Flushing 170 series with 18159 points and 967350 bytes from partition 1
[wal] 2015/09/18 02:54:10 Flush due to idle. Flushing 3586 series with 26962 points and 3657323 bytes from partition 1
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 86738c95-5db0-11e5-b056-000000000000 5.000761073s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 867393a5-5db0-11e5-b057-000000000000 5.000729647s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 86738bc2-5db0-11e5-b055-000000000000 5.001165028s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 8673bd16-5db0-11e5-b058-000000000000 5.000585795s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 86741da2-5db0-11e5-b059-000000000000 5.000806163s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 8674882e-5db0-11e5-b05b-000000000000 5.000872165s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 86748739-5db0-11e5-b05a-000000000000 5.001003338s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 86748f49-5db0-11e5-b05c-000000000000 5.000976884s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 8675a644-5db0-11e5-b05d-000000000000 5.000734955s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 8675da27-5db0-11e5-b05e-000000000000 5.000780546s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 8676aa5e-5db0-11e5-b05f-000000000000 5.00076614s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 8676ef3c-5db0-11e5-b060-000000000000 5.000874004s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 86774fc2-5db0-11e5-b061-000000000000 5.000810524s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 86777019-5db0-11e5-b062-000000000000 5.001051703s
[http] 2015/09/18 02:54:10 10.50.130.75 - root [18/Sep/2015:02:54:05 +0000] POST /write?consistency=one&db=tenant_0a9faca93d4742f7aeb94c459fcbdf15&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 8677839a-5db0-11e5-b063-000000000000 5.001026917s
[http] 2015/09/18 02:54:11 10.50.130.75 - root [18/Sep/2015:02:54:06 +0000] POST /write?consistency=one&db=tenant_c723e4f7bf364baeb1f6fbb2b41011f6&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 870740c1-5db0-11e5-b067-000000000000 5.001594968s
[http] 2015/09/18 02:54:11 10.50.130.75 - root [18/Sep/2015:02:54:06 +0000] POST /write?consistency=one&db=tenant_c723e4f7bf364baeb1f6fbb2b41011f6&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 87073e19-5db0-11e5-b066-000000000000 5.001673715s
[http] 2015/09/18 02:54:11 10.50.130.75 - root [18/Sep/2015:02:54:06 +0000] POST /write?consistency=one&db=tenant_c723e4f7bf364baeb1f6fbb2b41011f6&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 87074bae-5db0-11e5-b068-000000000000 5.001586573s
[http] 2015/09/18 02:54:11 10.50.130.75 - root [18/Sep/2015:02:54:06 +0000] POST /write?consistency=one&db=tenant_c723e4f7bf364baeb1f6fbb2b41011f6&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 87073256-5db0-11e5-b064-000000000000 5.002341997s
[http] 2015/09/18 02:54:11 10.50.130.75 - root [18/Sep/2015:02:54:06 +0000] POST /write?consistency=one&db=tenant_c723e4f7bf364baeb1f6fbb2b41011f6&p=%5BREDACTED%5D&precision=n&rp=default&u=root HTTP/1.1 500 32 - okhttp/2.4.0 87073cb6-5db0-11e5-b065-000000000000 5.002248086s

here is an image of the stats we are collecting from _internal database
<img width="600" alt="screen shot 2015-09-17 at 7 59 20 pm" src="https://cloud.githubusercontent.com/assets/5661189/9951075/e295964a-5d76-11e5-93d3-0c5db21ff00c.png">

**Comment by saravananvs** [comment]
Hi,
  I started exploring InfluxDB and ran into same issue with version 0.9.4.1.

Flushing takes lot of time (in my case it took close to 19 mins for 620K series). Please refer below logs

[wal] 2015/10/01 12:48:36 Flush due to memory. Flushing 620000 series with 620000 points and 21700000 bytes from partition 1

[wal] 2015/10/01 13:07:20 write to index of partition 1 took 18m44.1748336s
[wal] 2015/10/01 13:08:04 Metadata flush took 8m58.9704412s

The server has 4 cores and 16 GB RAM.

Here is the configuration

[data]
  engine = "bz1"
  max-wal-size = 104857600
  wal-flush-interval = "2m0s"
  wal-partition-flush-delay = "2s"
  wal-logging-enabled = true
  wal-ready-series-size = 30720
  wal-compaction-threshold = 0.5
  wal-max-series-size = 1048576
  wal-flush-cold-interval = "10m"
  wal-partition-size-threshold = 20971520
  query-log-enabled = true

**Comment by KiNgMaR** [comment]
Update from 0.9.5-nightly-64cef0f: no more timeouts, overall great performance, but still leaking a lot of memory and OOM'ing after a few hours.

**Comment by otoolep** [comment]
@KiNgMaR -- how do you know it is a leak? Are you tracking RSS for the influxd process?

**Comment by otoolep** [comment]
And @KiNgMaR -- did you change your engine? If you're still on `bz1` you are running the same engine as ever. Is it your intention to try out the new `tsm1` engine?

**Comment by KiNgMaR** [comment]
Hi @otoolep, yes tsm1 is used exclusively.

It looks like the growing memory is related to the index flush from the WAL. I made a simple log file that tracks memory usage. It can be correlated against the `flush to index took` entries in the influxdb.log file very easily. Here's the gist:

    # grep -P 'flush to index took [\d.]+s' /var/log/influxdb/influxd.log
    [tsm1wal] 2015/10/09 07:59:18 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 2.726795084s
    [tsm1wal] 2015/10/09 08:03:45 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 6.140263472s
    [tsm1wal] 2015/10/09 08:08:58 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 8.834235482s
    [tsm1wal] 2015/10/09 08:13:35 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 11.25431678s
    [tsm1wal] 2015/10/09 08:18:08 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 13.181981543s
    [tsm1wal] 2015/10/09 08:22:47 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 14.84928816s
    [tsm1wal] 2015/10/09 08:28:03 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 17.317131844s
    [tsm1wal] 2015/10/09 08:33:03 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 19.522796355s
    [tsm1wal] 2015/10/09 08:38:12 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 21.060538741s
    [tsm1wal] 2015/10/09 08:45:13 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 23.749604097s
    [tsm1wal] 2015/10/09 08:51:54 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 25.542913184s
    [tsm1wal] 2015/10/09 08:58:48 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 27.776700584s
    [tsm1wal] 2015/10/09 09:04:31 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 29.923418532s
    [tsm1wal] 2015/10/09 09:09:55 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 32.794877166s
    [tsm1wal] 2015/10/09 09:14:36 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 33.967796218s
    [tsm1wal] 2015/10/09 09:19:33 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 36.403752239s
    [tsm1wal] 2015/10/09 09:24:47 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 39.106057756s
    [tsm1wal] 2015/10/09 09:29:59 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 41.738886357s
    [tsm1wal] 2015/10/09 09:34:42 /var/opt/influxdb/data/xxx_prod/default/2 flush to index took 43.347510438s

    TIME     RSS
    07:59:06 660272
    07:59:16 753816
    07:59:26 791616
    07:59:36 791636
    07:59:46 791644
    07:59:56 791648
    08:03:07 915040
    08:03:17 915040
    08:03:27 915044
    08:03:37 917900
    08:03:47 1195092
    08:03:57 1197888
    08:08:07 1203032
    08:08:17 1203040
    08:08:27 1203040
    08:08:37 1203052
    08:08:47 1203052
    08:08:57 1464120
    08:13:08 1472276
    08:13:18 1472280
    08:13:28 1473772
    08:13:38 1833716
    08:13:48 1881820
    08:13:58 1881820
    08:18:08 2160248
    08:18:18 2168524
    08:18:28 2168532
    08:18:38 2168552
    08:18:48 2168552
    08:18:58 2168552
    08:22:09 2168604
    08:22:19 2168608
    08:22:29 2168608
    08:22:39 2168932
    08:22:49 2343480
    08:22:59 2343484
    08:28:09 2922080
    08:28:19 2920060
    08:28:29 2920060
    08:28:39 2920080
    08:28:49 2920080
    08:28:59 2920080
    08:33:00 2943488
    08:33:10 2951828
    08:33:20 2951828
    08:33:30 2951828
    08:33:40 2951840
    08:33:50 2951840
    08:38:00 3148904
    08:38:10 3172156
    08:38:20 3182472
    08:38:30 3182472
    08:38:40 3182492
    08:38:50 3182500
    08:45:01 3126352
    08:45:11 3665212
    08:45:21 3778876
    08:45:31 3780716
    08:45:41 3781312
    08:45:51 3781416
    08:51:01 2520904
    08:51:11 2520904
    08:51:22 2520904
    08:51:32 2572372
    08:51:42 2912276
    08:51:52 3843024
    08:58:02 3949264
    08:58:12 3949264
    08:58:22 3950044
    08:58:32 2839764
    08:58:42 3845884
    08:58:52 4042420
    09:04:03 4042496
    09:04:13 4042496
    09:04:23 4080136
    09:04:33 4091784
    09:04:43 4091784
    09:04:53 4091784
    09:08:03 4091840
    09:08:13 4091840
    09:08:33 4091860
    09:09:04 4091860
    09:09:14 4091860
    09:09:24 4347860
    09:09:34 4380640
    09:09:44 4394556
    09:09:54 4430156
    09:14:04 4711940
    09:14:14 4712336
    09:14:24 4761696
    09:14:34 4761912
    09:14:44 4770812
    09:14:54 4770820
    09:19:05 4758848
    09:19:15 4758852
    09:19:25 5154980
    09:19:35 5164060
    09:24:05 5164132
    09:24:15 5164132
    09:24:25 5168000
    09:24:35 5838672
    09:24:45 6233944
    09:24:55 6291920
    09:29:06 6294416
    09:29:16 6294416
    09:29:26 6294416
    09:29:36 6295068
    09:29:46 6303940
    09:29:56 6303956
    09:34:06 6313620
    09:34:17 6313620
    09:34:27 6314056
    09:34:37 6769228
    09:34:47 6780404
    09:34:57 6780412

Let me know if you need all the details, and where I can upload them. My current configuration is this: https://gist.github.com/KiNgMaR/2f0ba7ca6af1f83f39bc

**Comment by otoolep** [comment]
I think this issue has become mixed with reports for multiple engines.

@KiNgMaR -- can you open a new ticket for issues specifically related to the `tsm1` engine? Tickets filed against older engines (like this one) are unlikely to be fixed.

**Comment by KiNgMaR** [comment]
Okay, fair enough.
