### ISSUE TITLE
Retention policy no effect

### ISSUE THREAD

**Issue by starkDbl07** [influxdb/influxdb#4234]
I am testing influxdb. Installed version is 0.9.4.1

I have created some retention policies as given below:
default	"1h0m0s"	1	true
5minavg	"720h0m0s"	1	false
30minavg	"2160h0m0s"	1	false
1houravg	"8760h0m0s"	1	false
1dayavg	"26304h0m0s"	1	false
1minavg	"168h0m0s"	1	false

Querying on same database for "default" retention policy as given above still returns old data. According to above, the default retention policy should not have data before 1h, isn't it?
But even query of a day ago condition does not return 0 as shown below.

=> select count(value) from "default"."srv.dns.ns21.network.eth0.tx_byte" where time < '2015-09-25T00:04:58Z'
Retult is:
1970-01-01T00:00:00Z	159

Is there any misconfiguration?

**Comment by otoolep** [comment]
How long have you waited for the data to be deleted? It does not happen immediately.

Check back in 30 minutes.

**Comment by starkDbl07** [comment]
The default retention policy is "1h". And its still returning data of a day ago (24h+), to be specific since I created the database. The policy was altered at "2015/09/25 13:23:16" and currently it is "Sat Sep 26 03:21:44 NPT 2015" according to my timezone. 

Its been around 15h since I altered the policy and still no effect.

**Comment by otoolep** [comment]
Show us the output of `SHOW SHARDS` please.

**Comment by starkDbl07** [comment]
id	start_time	end_time	expiry_time	owners
2	"2015-09-21T00:00:00Z"	"2015-09-28T00:00:00Z"	"2015-09-28T01:00:00Z"	"1"
5	"2015-09-25T00:00:00Z"	"2015-09-26T00:00:00Z"	"2015-10-26T00:00:00Z"	"1"
7	"2015-09-25T00:00:00Z"	"2015-09-26T00:00:00Z"	"2015-10-03T00:00:00Z"	"1"
6	"2015-09-25T09:00:00Z"	"2015-09-25T10:00:00Z"	"2015-10-02T10:00:00Z"	"1"

**Comment by otoolep** [comment]
Can we see `SHOW RETENTION POLICIES ON <the target>` database?

**Comment by starkDbl07** [comment]
I posted the output of the same command on my first comment.

**Comment by starkDbl07** [comment]
is there any mistakes or missing portion in my configuration?

**Comment by otoolep** [comment]
I need to take a look at the code, to see what is going on.

**Comment by starkDbl07** [comment]
okay otoolep. 
i will be waiting for the solution.

**Comment by otoolep** [comment]
The issue is the following. When the database was first created, the default policy was given "infinite retention" which means each shard that was created when data was first written to the database will be around for 7 days. For example, this shard: 

 6 "2015-09-25T09:00:00Z" "2015-09-25T10:00:00Z" "2015-10-02T10:00:00Z" "1"

When you change the retention policy duration it does not affect shards already created. Only shards created after that point will be affected. You are seeing data in the shards created before you changed the policy, and that data will not be deleted for a few more days.

The best way to avoid this to either turn off auto-generation of the default retention policy (through the config file) which means you will need to explicitly create the retention policy, or change the retention duration before you write any data at all.

The system is behaving as coded. Any questions, let me know.

**Comment by starkDbl07** [comment]
thanks @otoolep 
is there anyway i can manually remove such shards?

**Comment by otoolep** [comment]
Not yet, but we hope to support that in the future.
