### ISSUE TITLE
Cannot connect localhost:8086 when tunnelling to InfluxDB UI

### ISSUE THREAD

**Issue by smalenfant** [influxdb/influxdb#4269]
I use `-L 8086:x.x.x.x:8086` to tunnel some private IP's on our network. InfluxDB UI does query directly from the browser.

Any way for InfluxDB UI to proxy the queries instead?

The workaround is to tunnel 8086 on localhost as well. But that means 1 connection possible.

**Comment by beckettsean** [comment]
@smalenfant there is no setting for the Admin UI to proxy requests, there's only the explicit connection setting to select the port (and that must match the config file setting as well.)

@rossmcdonald any thoughts on how this might work?

**Comment by rossmcdonald** [comment]
@smalenfant I think the easiest solution would be to proxy the communication at the browser level. You can do this directly using SSH's `-D <port>` option (opening a SOCKS proxy), or you can use a more robust solution such as squid or polipo if you will have multiple people/services connecting at once. Once you have the proxy setup, you can modify the settings in your browser (or use a plugin) to forward the communication over the proxy instead of trying to query Influx directly.

I hope that helps!
