### ISSUE TITLE
inserting tags with speech marks

### ISSUE THREAD

**Issue by yee379** [influxdb/influxdb#4297]
so i inadvertently added some data with double quotes around the tags:

```blah,device="hosta.example.com",item="some_1" key=123.0```

to my surprise, they got inserted into influx with the double quotes as part of the data. not a big deal, i'll just delete them i thought (after cleaning up the quotes from my little script).

however, 

```drop series from "blah" where device /.example.com/
ERR: error parsing query: found ., expected identifier, string, number, bool at line 1, char 39```

hmm... i guess regexp's aren't supported yet?

let's try deleting one of them...

```drop series from "cpdu" where device="hosta.example.com"```

seems to take ages.... doesn't return. it's been over 10 minutes now and i had only inserted one data point (there is a bunch of writes happening in the background tho)... is this even the right syntax to delete that single series with the quotes? can i do a regexp purge?

a ctrl-c from the CLI requires me to `reset` my terminal.

**Comment by beckettsean** [comment]
`drop series from "blah" where device /.example.com/` is incorrect syntax. Regex requires an operator. The proper syntax would be `drop series from "blah" where device =~ /.example.com/`

However, there's a bug in the parser that leads to over-greedy matching: https://github.com/influxdb/influxdb/issues/4276. I wouldn't use regex with `DROP SERIES` until that is addressed (should be fixed in 0.9.5).

For the second query, the quoting rules for writes and queries are different. Double-quoting in queries is for identifiers, single-quoting is for strings. In the original query, `where device="hosta.example.com"` is actually parsing as "where `device` equals another tag or field (identifier) called `"hosta.example.com"`". The actual tag value string is `"hosta.example.com"` and since it's a string it needs to be single-quoted.

Try `drop series from "cpdu" where device='"hosta.example.com"'`

> a ctrl-c from the CLI requires me to reset my terminal.

Known issue: https://github.com/influxdb/influxdb/issues/2609
