### ISSUE TITLE
[0.9.4.2] ALTER RETENTION POLICY doesn't update existing shards

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#4441]
This is tough to test but my experiments suggest that the expiry time of a shard cannot be altered once it is created. This means `ALTER RETENTION POLICY` leads to unexpected behaviors.

1. Current RP is `INF`, update it to 1 hour. New data is dropped after an hour but existing data will be retained forever.
1. Current RP is 1 hour, update it to `INF`. New data is kept forever but existing data is still dropped after an hour.

Effectively the duration in place when the point is written controls forever and cannot be changed. Seems as though the ALTER RP query should be able to change the expiry dates as appropriate on the existing shards.

**Comment by otoolep** [comment]
The root cause of this is that the end-time of shards for INF policies (which is what it was when the shard was created) is 30 days in the future.

This means that the data won't be deleted until that time has been reached.

**Comment by otoolep** [comment]
After discussions with @beckettsean there is nothing to do here.

otoolep 12:48 The retention policy issue with ALTER DURATION
I am not sure we can fix it.
With infinite retention, shards are created with 30d periods.
So say I drop duration to 1d.
What do I do?
The start time of the shard was (say) now, and the end time is 30 days in the future.
Unless you see a way to solve this?
sean 13:04 I think I’d need to see it on a whiteboard to really understand the limitations
also I thought we had 7 day shards for any duration > 6 months?
oh, but the end time is 30 days, not the timespan
otoolep 13:05 Maybe, I'd need to check the code.
The point is that the endtime is in the future.
The code could go in and re-adjust that endpoint, but that may make data invsisible.
See?
sean 13:05 no
maybe ALTER DURATION only immediately impacts cold shards?
otoolep 13:06 Define cold.
sean 13:07 shards that aren’t hot for writes now
So if I have 7 day shards
anything with data 8+ days old
otoolep 13:07 But that already works.
sean 13:08 not in my experience, or perhaps I misunderstood what I was seing
otoolep 13:08 Imagine I create a 7 day shard starting now. 4 days pass. I am still writing to that shard. I change duration to 1 day. I cannot delete the shard. (edited)
sean 13:08 agreed
otoolep 13:08 You're saying delete the shard before that one?
OK, I think I follow you.
sean 13:09 Shard A is 10-1 through 10-7, Shard B is 10-8 through 10-15. On 10-12 I change the duration to 1d. Shard A immediately drops, Shard B drops on 10-16 (edited)
otoolep 13:10 OK
Yeah
Let me double check the code to see if we can make that happen.
Right, OK, well in that case the moment you make the change those shards are up for deletion immediately, as I thought.
https://github.com/influxdb/influxdb/blob/master/meta/data.go#L887
So it will work now in the case you outlined. (edited)
sean 13:15 cool, that seems like the expected behavior
otoolep 13:15 It get's confusing if you changed the duration to, say, 1d.
Then you're stuck with 7 days of data, for the week. (edited)
Agreed?
sean 13:17 yeah, but I think there’s nothing else we can do unless we refactor the hot shard into multiple shards of the new duration, which seems very CPU intensive.

OK, I think the ticket should be closed.
Seems we're reasoned the way it works is the way it will work.
