### ISSUE TITLE
[0.9.5-nightly] SHOW TAG VALUES ... WHERE time > now() - 1h

### ISSUE THREAD

**Issue by ymettier** [influxdb/influxdb#4471]
Hello,

## Description of the problem
```
SHOW TAG VALUES FROM "sys.cpu" WITH KEY = "fqdn" WHERE time > now() - 1h
```

This is returning results on 0.9.4

0.9.5-nightly answers this :
```
Server returned error: SHOW SERIES doesn't support time in WHERE clause
```

How can I get the servers that were still alive last hour ?

## More information
```
$ rpm -q influxdb
influxdb-0.9.5_nightly_542efbb-1.x86_64
```
and
```
SHOW DIAGNOSTICS
[...]
Branch	Build Time	Commit	Version
master	"'2015-10-16T04:00:42+0000'"	"542efbbd7993f0a7a7e6ff73a134df13c8274744"	"0.9.5-nightly-542efbb"
```
Regards,
Yves

**Comment by ymettier** [comment]
I forgot to mention that I'm running `tsm1` engine. I don't know if this is important. Not tested with `bz1`.

**Comment by mimmovele** [comment]
+1, ```tsm1``` engine

**Comment by otoolep** [comment]
This syntax is not supported, since tag values are not indexed by time.

Perhaps try querying, for the last hour, for a value all servers should be emitting, and then do a GROUP BY 'fqdn'. Servers that have not emitted anything will have zero results.

**Comment by otoolep** [comment]
I am mistaken, as we can look at the shards by time.

CC @dgnorton for comment.

@dgnorton -- is this a regression?

**Comment by otoolep** [comment]
Re-opening a ticket.

**Comment by dgnorton** [comment]
@otoolep It's not a regression.  `SHOW TAG VALUES` does not support `WHERE time...` because it's a meta query and does not hit the shards...only the index.  It doesn't know time ranges that tags are available for.  The error message it's reporting now...`SHOW SERIES...`...is a copy/paste error on my part, which I'll fix now.

@ymettier testing a solution to your question  `How can I get the servers that were still alive last hour ?` and will reply on this issue soon.

**Comment by otoolep** [comment]
Thanks @dgnorton -- that's what I though so I originally closed the bug but was then trying to come up with a way how it could have worked. So the `WHERE` clause was simply being ignored previously giving the impression it worked, correct?

**Comment by dgnorton** [comment]
@otoolep `Measurement.idsForExpr()` in `tsdb.meta.go` returns all series IDs for the measurement if there is a `time` expression.  https://github.com/influxdb/influxdb/blob/master/tsdb/meta.go#L782
Then, `QueryExecutor.executeShowTagValuesStatement` returns all tag values for all tag keys.  So, instead of filtering by `time`, it returns everything.

**Comment by otoolep** [comment]
@ymettier -- this query was never working the way you thought. It always ignored the `WHERE` clause, but we have fixed that now in current software such that error is returned (though the error was not the correct message, and that has also just been fixed).

This is all what I originally thought, which is why I closed the ticket in the first place.

**Comment by beckettsean** [comment]
duplicate of https://github.com/influxdb/influxdb/issues/4029

**Comment by dgnorton** [comment]
@ymettier To get the servers that were alive the last hour, you can use a `SELECT` query.  For example,

```
> select * from cpu
name: cpu
---------
time			fqdn	value
1445262814569499855	bar	10
1445262876312503941	zoo	33.3
1445262982368712403	dog	19.8

> select fqdn, value from cpu where time > now() - 3m
name: cpu
---------
time			fqdn	value
1445262982368712403	dog	19.8
```

**Comment by martinei** [comment]
The proposed workaround does not work if the metric was reported twice per host within the time range.

**Comment by ymettier** [comment]
Maybe `GROUP BY fqdn` can help ? Not tested yet.
