### ISSUE TITLE
Add boolean operator to check for null values (and its inverse, i.e. not null)

### ISSUE THREAD

**Issue by jvshahid** [influxdb/influxdb#454]
`column1 not null` or `column1 <> null`. Feedback is welcome.

**Comment by sevastos** [comment]
+1

**Comment by dandv** [comment]
@beckettsean: [can the docs elaborate on why this was closed](https://github.com/influxdata/docs.influxdata.com/issues/717)? Given that series can have nulls, it seems like a really useful feature to be able to count null values and have them in WHERE clauses.

In practice, I'm running into a wall trying to extract points from a series that have some null fields, and other fields with undesired values, since [deleting by field values doesn't work](http://stackoverflow.com/questions/39685114/delete-points-with-unwanted-field-values-from-influxdb-measurement).

**Comment by mitar** [comment]
I think the proposed solution is to have two fields, one for nulls, and one for values. So we [use `value` and `value_null`](https://github.com/wlanslovenija/datastream/blob/master/datastream/backends/influxdb.py#L581) for each value. One is set only when the value is null.

**Comment by dandv** [comment]
Sure, but if you inherit a measurement with nulls, then what?

**Comment by beckettsean** [comment]
@dandv InfluxDB 0.9+ doesn't store nulls, so there's nothing to count. I'm not sure what you mean about inheriting a measurement with nulls.

**Comment by dandv** [comment]
You could in theory inherit a time series created before v0.10 (not sure if this is actually possible, or you have to reimport instead of just upgrading influxd).

Anyway, my question is about querying for null values, not whether they're stored or not, since [queries do return null values](https://github.com/influxdata/docs.influxdata.com/issues/717#issuecomment-249661093).

**Comment by ExplodingCabbage** [comment]
This issue ought to be reopened. The team seems to think that what's being asked for here is fundamentally incoherent, but it isn't.

@beckettsean 

> InfluxDB 0.9+ doesn't store nulls, so there's nothing to count.

Sure there is - rows where the field *isn't present*, which is what would cause InfluxDB to return a null for that field in the result set. The fact that InfluxDB "doesn't store" the null is an implementation detail that doesn't matter from a user's perspective; I'm not even sure I know what it *means*, to be honest.

If you want to retitle the issue to "Add boolean operator to check for missing values", then sure, go ahead. But there's a perfectly clear and coherent request here with real use cases and [>5k Stack Overflow views](https://stackoverflow.com/q/30091980/1709587) from people wanting it, and the entire current argument for not rejecting it seems to be some sophistry regarding implementation details of the storage engine that surely ought to be entirely abstracted away from the end user anyway.

**Comment by spali** [comment]
My specific usecase is from telegraf input ping plugin:
```
[[inputs.ping]]
count = 1
deadline = 10
interface = ""
ping_interval = 1.0
timeout = 1.0
urls = ["1.1.1.1","1.1.1.2","1.1.1.3"]
```
the plugin stores all expected fields when the ping was a success.
But a timeout does only fill the `result_code` field. And `result_code` for timeout is `0` (same as success).
```
SELECT "result_code" FROM "ping" GROUP BY "url" ORDER BY time DESC LIMIT 1
```
returns all a row.
```
SELECT "average_response_ms" FROM "ping" GROUP BY "url" ORDER BY time DESC LIMIT 1
```
omits the row that was a ping timeout because average_response_ms is null (or does not exists as told by the devs).

But how can I determine if last row has `null` in `average_response_ms`.
At the end, the use case is to get a result with all url's where I see which didn't respond.
1.1.1.1 UP
1.1.1.2 UP
1.1.1.3 DOWN

Something like `nvl` would allow to replace the non existing `average_response_ms` with something I can handle. Or explicitly query for all `url` where `average_response_ms` is null would allow me to list exactly all of these.

**Comment by ash0080** [comment]
Anyone can tell me how to exclude a filed is null when work with GROUP BY？
For example:
```
SHOPNAME  MESSAGE
                      "hello"
"A"                 "world"
"B"                "welcome"

```

**Comment by dandv** [comment]
Influx team, any chance to reopen this issue if it's rephrased [in InfluxDB terms](https://www.influxdata.com/blog/tldr-influxdb-tech-tips-february-16-2017/)?

"Add boolean operator to check for **Blank Field Values**"
