### ISSUE TITLE
drop measurement does not free storage

### ISSUE THREAD

**Issue by szelok** [influxdb/influxdb#4717]
I had 0.9.2 installed on Linux. I ran a drop measurement. But the disk storage did not seem to be returned to the OS. Do I miss any configurations?

And it seemed it's holding onto the space and not even using them for new data points.

Worse still, the memory usage (rss) shot up to roof while/after drop measurement. Even after restart.the memory was still very high.

**Comment by beckettsean** [comment]
DROP MEASUREMENT will not necessarily free up space due to the nature of the storage engine. To guarantee free disk space you need to use retention policies to drop shards or `DROP DATABASE`.

> And it seemed it's holding onto the space and not even using them for new data points.

The storage engine files are not 100% dense. They leave some blank space in the organization to allow for additional points and prevent huge amounts of I/O when a new point must be added.

Unrelated, but 0.9.2 is quite old. Can you upgrade to 0.9.4+? RAM issues are significantly reduced in 0.9.4 and 0.9.5, which is coming soon.

**Comment by GerryLon** [comment]
I'm using influxdb 1.7.10, also have the same problem. 
Any suggestions?

Many Thanks!
