### ISSUE TITLE
[0.9.5] What's the best way to load massive data?

### ISSUE THREAD

**Issue by changhuilin** [influxdb/influxdb#4936]
I am currently using Java HTTP client API to load data, with batch size 1000 ~ 10000. The maximum throughput I can see is around 17K/s (I tried to config data storage in HDD or SSD, but the performance seems similar). I think there is overhead caused by HTTP requests. 

I am wondering if there is any better way to load data, without going through HTTP requests (interacting with storage engine directly).

**Comment by ivanscattergood** [comment]
@changhuilin is that 17k per second? I'm writing using the Java HTTP client API and I'm getting a much lower write speed (around 300 per sec). 

What spec box are you using?  Are you using the tsm1 engine?

**Comment by changhuilin** [comment]
@ivanscattergood Yes, that's 17K/s. Probably you did not enable batch (InfluxDB.enableBatch())?

**Comment by ivanscattergood** [comment]
I am writing in batches - although I manage these myself due to the source of the data. I write the data when it reaches 10,000 records or 20 min whichever is earlier. 

I still get timeouts when writing data, if it fails once I hold off and retry. On the second failed attempt I throw the data away.

What spec box are you using? Are you using the tsm1 engine?

**Comment by changhuilin** [comment]
@ivanscattergood  
Yes, I configured to use tsm1.
Our server has 64G RAM, Intel Xeon CPU E5-2670 v2 @ 2.50GHz, SSD/HDD (although I did not see much difference between ssd and hdd in the case of my loaded data).

One thing is, the data I tested only has a few series (<10). This might affect the performance (if you have many series)?

btw, I do not understand why you have to mange batch by yourself; it seems having nothing to do with data source? Anyway, I do not think it causes the performance problem.

**Comment by beckettsean** [comment]
@changhuilin a server with a Xeon CPU and 64GB of RAM, running an SSD should be capable of 100k writes per second without breaking a sweat. If you can only get 17k pps then something else is going on.

You mentioned you are writing with 5-10k points per batch, that's great.
You only have a few dozen series, which means there should be no overhead from that.

Are you supplying timestamps with the points?
If so, are they in ascending chronological order, descending order, or random order within a batch?

Are you writing points to the recent past, or are the points more than a month old, or in the future?

Are you using the line protocol?

**Comment by changhuilin** [comment]
@beckettsean 

>Are you supplying timestamps with the points?
>If so, are they in ascending chronological order, descending order, or random order within a batch?
-- Yes, the loaded data has timestamps in ascending chronological order (we are targeting sensor generated data).

> Are you writing points to the recent past, or are the points more than a month old, or in the future?
-- The supplied timestamps are a couple of years old. But how does this affect load performance?

> Are you using the line protocol?
-- I am using Java HTTP client API (https://github.com/influxdb/influxdb-java). How is the performance 100K pps obtained (which API)? Any native API to directly talk to the storage engine?

Thanks.

**Comment by beckettsean** [comment]
> Any native API to directly talk to the storage engine?

https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html. Any client libraries are just wrappers around this API for use in specific languages. 

> The supplied timestamps are a couple of years old. But how does this affect load performance?

One of the assumptions in the system is that points are from the recent past. There are internal equivalents of pre-fetching and just-in-time allocation that may not function as well if that assumption is not true.

Please try submitting points directly via the HTTP API, rather than the Java library. Specifically the "Write a Batch of Points with `curl`" section on the page referenced above.

**Comment by changhuilin** [comment]
@beckettsean 
Thanks. I will try to use curl for batch loading. My understanding is, if I have a large dataset, I need to separate them to multiple files (batches), and use curl to load them one by one. Am I right?

Besides, by "native API", I mean native programming API to storage engine, bypassing HTTP. So if there are streaming data with high volume/velocity, we can use native API to write data (instead of batching data in a file following line protocol, and then call curl api). 
I think, to load a  batch using curl HTTP API, internally, influxdb needs to parse each point in the file, and then insert the point to the database? I think it would be useful to have API for the insertion here.

**Comment by beckettsean** [comment]
>  I need to separate them to multiple files (batches), and use curl to load them one by one. Am I right?

Correct. Submit via curl in batches of 5,000 - 25,000 points per file. E.g. `curl -XPOST 'http://localhost:8086/write?db=mydb' --data-binary @file`

There are five ways to write to InfluxDB: 
 - HTTP API (localhost:8086/write)
 - UDP (localhost:xxxx)
 - Graphite protocol (localhost:2003)
 - collectd protocol (localhost:xxxx)
 - OpenTSDB protocol (localhost:4242)

The first two go through the line protocol parser. UDP is faster because the protocol is more lightweight, but it can be lossy since there's no acknowledgement of receipt. The latter three protocols use write protocols from other projects. They may or may not be faster than submitting line protocol, I honestly don't know, but likely it would be more work to rearchitect to one of those, and I think it's unlikely to make a significant improvement in write performance.

Given this issue and https://github.com/influxdb/influxdb/issues/4950 I'm beginning to suspect that the `influxdb-java` client has some serious write performance issues. I've asked the team to do some perf testing with that library when they get a chance.

**Comment by otoolep** [comment]
@beckettsean -- anything more we can do here? Close?
