### ISSUE TITLE
How to upgrade from 0.9.3 to 0.9.6

### ISSUE THREAD

**Issue by lynch0227** [influxdb/influxdb#5104]
Hi guys,

What's the best practice to upgrade to new version, like from 0.9.3 to 0.9.6?
1. install the new version
2. stop the old version
3. copy the data folder from old version to new version
4. start the new version

Is that all right? do you have any suggestion?

Thank you.

**Comment by rossmcdonald** [comment]
@lynch0227 There is no need to move the data folders, since the configuration is automatically copied over. For a generic upgrade, you can just:

1. Install the new version
2. Restart the service (stops old service, starts new service)

Where the only directory that should have changed was your configuration (`/etc/opt/influxdb` to `/etc/influxdb`). If you run into any issues, double check your configuration to make sure it's pointing to the right data directories. 

Also be sure to check out the [CHANGELOG](https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md) for any relevant changes that may affect your installation (especially the changes to the filesystem hierarchy).

I hope that helps!
