### ISSUE TITLE
Why retention policy can't be shorter than/must be at least 1 hour?

### ISSUE THREAD

**Issue by zstyblik** [influxdb/influxdb#5198]
Hello,

I'm wondering why you can't `CREATE RETENTION POLICY` shorter than 1 hour.

```
> USE testdb
Using database testdb
> CREATE RETENTION POLICY foo ON testdb DURATION 30m REPLICATION 1
ERR: retention policy duration must be at least 1h0m0s
```

As for why, well, the ease of testing.

Thanks.

**Comment by naxhh** [comment]
I'll guess is because DROP has a high cost in influx and you don't want to be removing stuff that often.

**Comment by otoolep** [comment]
Dropping due to retention enforcement is actually low cost, since it's just the deletion of files.

We had to have *some* minimum duration since we wanted to prevent nonsensical stuff like retention durations of, say, 1 millisecond.

InfluxDB is open-source. You can always change the minimum yourself and build. :-)

https://github.com/influxdb/influxdb/blob/master/meta/data.go#L23

**Comment by zstyblik** [comment]
@otoolep that doesn't really make sense, but given you reply ... whatever. I feel sorry for asking.

**Comment by MaxPleaner** [comment]
Realize this is an old thread but there's a very big difference between 1 millisecond as a min retention time and 1 hour. The latter makes it difficult to write a quick test, because I have to wait an hour to see if the data was deleted.

**Comment by otoolep** [comment]
I accept that time-driven tests are important, you can potentially mock out the time package somehow, and force its time forward.

**Comment by maxp-edcast** [comment]
@otooltep I don't know how to do that. I don't even know GoLang.

**Comment by swertz** [comment]
This is old, but I also don't see why there should be a minimum of 1h... For testing purposes it's very annoying. Hell, even 1ms, that choice should be left up to the user...
