### ISSUE TITLE
[0.9.6.1] Grouping by more than time(1h) returns ranges that are shifted

### ISSUE THREAD

**Issue by francisdb** [influxdb/influxdb#5200]
Might be a misunderstanding from my side or related to time zone support being missing but I'm trying the following

```
SELECT MEAN("value")
FROM "steps"
WHERE "resource"='foobar'
AND time >= 1450738800000ms AND time < 1450800947231ms
GROUP BY time(4h)
LIMIT 10000
```

for any grouping below 1h the first returned item will have a timestamp of 1450738800000 but when using for example time(4h) the first timestamp is off by -3h (1 - #groupinghours)

Is this expected? I don't see this behaviour when using minutes or seconds.

**Comment by beckettsean** [comment]
@francisdb GROUP BY time interval boundaries are not determined by the `WHERE time` clause. A `GROUP BY time(4h)` query will always return buckets starting at 00:00, 04:00, 08:00, 12:00, 16:00, and 20:00 UTC, regardless of the upper and lower bounds of the time range in the WHERE clause.

This is not intuitive, and is not a long-term design decision, it's just what we have right now because it's the easiest to implement.

See https://github.com/influxdb/influxdb/issues/1837 for more context on the future development of GROUP BY windows.
