### ISSUE TITLE
Query parser should respect the `time_precision` query param if no precision is given in the query

### ISSUE THREAD

**Issue by jvshahid** [influxdb/influxdb#574]
When a user issues `select * from time < 1234`, `1234` should be interpreted using the time_precision specified in the url and falls back to nanoseconds if no time precision was specified in the url. `select * from time < 1234<prefix>` should be backward compatible and the prefix specified the time precision in this case.

**Comment by salanki** [comment]
Closed due to?

**Comment by beckettsean** [comment]
Closed due to extreme age. This issue is 1 year old with zero updates and no other mentions in issues or PRs. I don't believe the precision can be supplied in the query string, anyway, it must be part of the JSON payload. If there are problems with time precision in the JSON payload that should be a new issue.

Also, nanosecond precision is likely not the right default if none is given.
